<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\controllers\base;

use app\models\AcreditacionEstudio;
use app\controllers\base\CatiController;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* AcreditacionEstudioController implements the CRUD actions for AcreditacionEstudio model.
*/
class AcreditacionEstudioController extends CatiController
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all AcreditacionEstudio models.
* @return mixed
*/
public function actionIndex()
{
    $dataProvider = new \yii\data\ActiveDataProvider([
    'query' => AcreditacionEstudio::find(),
    ]);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
]);
}

/**
* Displays a single AcreditacionEstudio model.
* @param integer $nk
*
* @return mixed
*/
public function actionView($nk)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($nk),
]);
}

/**
* Creates a new AcreditacionEstudio model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new AcreditacionEstudio;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'nk' => $model->nk]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing AcreditacionEstudio model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $nk
* @return mixed
*/
public function actionUpdate($nk)
{
$model = $this->findModel($nk);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing AcreditacionEstudio model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $nk
* @return mixed
*/
public function actionDelete($nk)
{
try {
$this->findModel($nk)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$nk',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the AcreditacionEstudio model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $nk
* @return AcreditacionEstudio the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($nk)
{
if (($model = AcreditacionEstudio::findOne($nk)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
