<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A' => 'Afín',
    'B' => 'Formación Básica',
    'C' => 'Complementaria',
    'E' => 'Prácticas externas',
    'F' => 'Fundamental',
    'I' => 'Investigación',
    'L' => 'Libre Elección',
    'M' => 'Metodológica',
    'O' => 'Obligatoria',
    'P' => 'Optativa',
    'R' => 'Complementos de Formación',
    'T' => 'Troncal',
    '1' => 'Practicum',
    '2' => 'Proyecto Fin de Carrera',
    '3' => 'Trabajo fin de Grado',
    '4' => 'Actividades Académicas Complementarias',
    '5' => 'Destrezas transversales',
    '6' => 'Trabajo fin de máster',
    '7' => 'Prácticas Extracurriculares',
];
