<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure to delete this item?' => '¿Seguro que desea borrar este elemento?',
    'Cancel' => 'Cancelar',
    'Copy' => 'Copiar',
    'Create' => 'Crear',
    'Delete' => 'Borrar',
    'Edit' => 'Editar',
    'First' => 'Primero',
    'Full list' => 'Lista completa',
    'Last' => 'Último',
    'List All' => 'Listar tod@s l@s',
    'New' => 'Nuev@',
    'Relations' => 'Relaciones',
    'Save' => 'Guardar',
    'Select' => 'Seleccionar',
    'View' => 'Ver',
    'Agentes' => '',
    'Centro' => '',
    'Correo electrónico' => '',
    'Cód. estudio' => '',
    'Cód. plan' => '',
    'Estudio' => '',
    'Fecha próxima renovación' => '',
    'Nombre y apellidos' => '',
    'Nuevo apartado' => '',
    'Nuevo delegado' => '',
    'URL de la acreditación institucional' => '',
    'URL de la web específica' => '',
    'URL del horario' => '',
];
