<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Coordinador' => '',
    'Estudiante' => '',
    'Experta externa del centro' => '',
    'Experta externa del rector' => '',
    'Experto externo del centro' => '',
    'Experto externo del rector' => '',
    'Miembro' => '',
    'PAS' => '',
    'Presidenta' => '',
    'Presidente' => '',
    'Profesor' => '',
    'Profesora' => '',
    'Secretaria' => '',
    'Secretario' => '',

    'Catedraticos de Universidad (CU)' => 'Catedráticos de universidad (CU)',
    'Profesor Titular universidad (TU)' => 'Profesor titular de universidad (TU)',
    'Catedratico escuela universitaria (CEU)' => 'Catedrático de escuela universitaria (CEU)',
    'Titular Escuela Universitaria (TEU, TEUL)' => 'Titular de escuela universitaria (TEU, TEUL)',
    'Profesor contratado doctor (COD, CODI)' => '',
    'Ayudante doctor (AYD)' => '',
    'Ayudante (AY)' => '',
    'Profesor colaborador (COL, COLEX)' => '',
    'Asociado (AS, ASCL)' => '',
    'Profesor asociado medico (ASCM)' => 'Profesor asociado médico (ASCM)',
    'Emerito (EMERPJ, EMER)' => 'Emérito (EMERPJ, EMER)',
    'Personal Investigador (INV, IJC, IRC, PIF, INVDGA)' => 'Personal investigador (INV, IJC, IRC, PIF, INVDGA)',
    'Invest posdoctorales formacion (POS)' => 'Invest posdoctorales formación (POS)',

    'Ayudante' => '',
    'Colaborador Extraordinario' => '',
    'Cuerpo de Catedráticos de Escuelas Universitarias' => '',
    'Cuerpo de Catedráticos de Universidad' => '',
    'Cuerpo de Profesores de Enseñanza Secundaria' => '',
    'Cuerpo de Profesores Titulares de Escuelas Universitarias' => '',
    'Cuerpo de Profesores Titulares de Universidad' => '',
    'Maestros' => '',
    'Otro personal docente' => '',
    'Personal Docente, Investigador o Técnico' => '',
    'Personal Investigador en Formación' => '',
    'Prof Adjunto de Escuela Univ.' => '',
    'Prof Auxiliar o Ayudante' => '',
    'Prof Ayudante Doctor' => '',
    'Prof Contratado Doctor' => '',
    'Prof Tit de Otras enseñanzas U' => '',
    'Prof Titular de Escuela Univ.' => '',
    'Profesor Asociado' => '',
    'Profesor Asociado en Ciencias de la Salud' => '',
    'Profesor Ayudante Doctor' => '',
    'Profesor Colaborador' => '',
    'Profesor Contratado Doctor' => '',
    'Profesor Emérito' => '',
    'Profesor Honorario' => '',
    'Profesor Titular de E.U. laboral' => '',

    'Presentación' => '',
    'Por qué cursar esta titulación' => '',
    'Perfil recomendado' => '',
    'Requisitos de acceso' => '',
    'Solicitud de admisión' => '',
    'Criterios y procedimientos de admisión' => '',
    'Adjudicación de plazas' => '',
    'Matrícula' => '',
    'Perfiles de salida' => '',
    'El entorno profesional y social en el que se ubica este estudio' => '',
    'Empresas e instituciones colaboradoras' => '',
    'Qué se aprende' => '',
    'Descripción detallada de las competencias que se adquieren en la titulación' => '',
    'Módulo de formación básica' => '',
    'Módulo de Química y análisis de los alimentos' => '',
    'Módulo de procesado e ingeniería de los alimentos' => '',
    'Módulo de Microbiología y Seguridad Alimentaria' => '',
    'Módulo de Gestión y Calidad en la Industria Alimentaria' => '',
    'Módulo de Nutrición y salud' => '',
    'Módulo de integración de enseñanzas' => '',
    'Presentación general del plan de estudios' => '',
    'Cuadro de distribución de materias por créditos' => '',
    'Referentes externos utilizados para el diseño de este título' => '',
    'Procedimientos de consulta utilizados para el diseño de este título' => '',
    'Acciones para la movilidad de los estudiantes' => '',
    'Sistema de orientación, información y apoyo académico para estudiantes' => '',
    'Asesorías, alojamiento y servicios' => '',
    'Actividades deportivas y culturales' => '',
    'Participación en la vida universitaria' => '',
    'Plan de acción tutorial en la Facultad de Veterinaria' => '',
    'El profesorado de esta titulación' => '',

    'Introducción' => '',
    'Contacto' => '',
    'Competencias básicas' => '',
    'Capacidades y destrezas personales' => '',
    'Otras competencias, específicas del programa' => '',
    'Acceso' => '',
    'Admisión' => '',
    'Complementos de formación' => '',
    'Supervisión de tesis' => '',
    'Seguimiento del doctorando' => '',
    'Otros procedimientos, específicos del programa' => '',
    'Formación transversal' => '',
    'Formación específica' => '',
    'Líneas de investigación' => '',
    'Recursos humanos' => '',
    'Recursos materiales' => '',

    'Oferta de grados y másteres universitarios' => '',

    'Comisión de Garantía de la Calidad Conjunta' => '',
    'Comisión de Evaluación de la Calidad' => '',
    'Comisión de Garantía de la Calidad' => '',
    'Coordinador del centro' => '',
];
