<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Estudio $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="estudio-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Estudio',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute tipoEstudio_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'tipoEstudio_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\TipoEstudio::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['tipoEstudio_id'])),
    ]
); ?>

<!-- attribute activo -->
			<?= $form->field($model, 'activo')->textInput() ?>

<!-- attribute anyo_academico -->
			<?= $form->field($model, 'anyo_academico')->textInput() ?>

<!-- attribute id_nk -->
			<?= $form->field($model, 'id_nk')->textInput() ?>

<!-- attribute codigo_mec -->
			<?= $form->field($model, 'codigo_mec')->textInput(['maxlength' => true]) ?>

<!-- attribute rama_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'rama_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Rama::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['rama_id'])),
    ]
); ?>

<!-- attribute nombre_coordinador -->
			<?= $form->field($model, 'nombre_coordinador')->textInput(['maxlength' => true]) ?>

<!-- attribute email_coordinador -->
			<?= $form->field($model, 'email_coordinador')->textInput(['maxlength' => true]) ?>

            <!-- attribute fecha_implantacion --> 
            <?= $form->field($model, 'fecha_implantacion')->textInput() ?> 

            <!-- attribute fecha_acreditacion --> 
           <?= $form->field($model, 'fecha_acreditacion')->textInput() ?>

           <!-- attribute anyos_evaluacion --> 
           <?= $form->field($model, 'anyos_evaluacion')->textInput() ?> 

        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'Estudio'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

