<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Plan $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="plan-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Plan',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute id_nk -->
			<?= $form->field($model, 'id_nk')->textInput() ?>

<!-- attribute estudio_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'estudio_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Estudio::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['estudio_id'])),
    ]
); ?>

<!-- attribute centro_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'centro_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Centro::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['centro_id'])),
    ]
); ?>

<!-- attribute creditos -->
			<?= $form->field($model, 'creditos')->textInput() ?>

<!-- attribute duracion -->
			<?= $form->field($model, 'duracion')->textInput() ?>

<!-- attribute nip_coordinador -->
			<?= $form->field($model, 'nip_coordinador')->textInput() ?>

<!-- attribute activo -->
			<?= $form->field($model, 'activo')->textInput() ?>

<!-- attribute en_extincion -->
			<?= $form->field($model, 'en_extincion')->textInput() ?>

<!-- attribute es_interuniversitario -->
			<?= $form->field($model, 'es_interuniversitario')->textInput() ?>

<!-- attribute coordina_uz -->
			<?= $form->field($model, 'coordina_uz')->textInput() ?>

<!-- attribute nuevo -->
			<?= $form->field($model, 'nuevo')->textInput() ?>

<!-- attribute compatible_men_esp -->
			<?= $form->field($model, 'compatible_men_esp')->textInput() ?>

<!-- attribute anyo_academico -->
			<?= $form->field($model, 'anyo_academico')->textInput() ?>

<!-- attribute estudio_id_nk -->
			<?= $form->field($model, 'estudio_id_nk')->textInput() ?>

<!-- attribute fecha_boe -->
			<?= $form->field($model, 'fecha_boe')->textInput() ?>

<!-- attribute normativa -->
			<?= $form->field($model, 'normativa')->textInput(['maxlength' => true]) ?>

<!-- attribute nombre_coordinador -->
			<?= $form->field($model, 'nombre_coordinador')->textInput(['maxlength' => true]) ?>

<!-- attribute nombre_delegado -->
			<?= $form->field($model, 'nombre_delegado')->textInput(['maxlength' => true]) ?>

<!-- attribute email_coordinador -->
			<?= $form->field($model, 'email_coordinador')->textInput(['maxlength' => true]) ?>

<!-- attribute email_delegado -->
			<?= $form->field($model, 'email_delegado')->textInput(['maxlength' => true]) ?>

<!-- attribute url_horarios -->
			<?= $form->field($model, 'url_horarios')->textInput(['maxlength' => true]) ?>

<!-- attribute url_web_plan -->
			<?= $form->field($model, 'url_web_plan')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'Plan'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

