<?php
/**
 * /home/quique/Devel/cati/cati/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var app\models\Agente $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="agente-form">

    <?php $form = ActiveForm::begin([
		'id' => 'Agente',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-error'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute centro_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'centro_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(app\models\Centro::find()->all(), 'id', 'id'),
	[
		'prompt' => Yii::t('cruds', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['centro_id'])),
	]
); ?>

<!-- attribute plan_id_nk -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'plan_id_nk')->dropDownList(
	\yii\helpers\ArrayHelper::map(app\models\Plan::find()->all(), 'id_nk', 'id'),
	[
		'prompt' => Yii::t('cruds', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['plan_id_nk'])),
	]
); ?>

<!-- attribute estudio_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'estudio_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(app\models\Estudio::find()->all(), 'id', 'id'),
	[
		'prompt' => Yii::t('cruds', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['estudio_id'])),
	]
); ?>

<!-- attribute comision_id -->
			<?php echo $form->field($model, 'comision_id')->textInput(['maxlength' => true]) ?>

<!-- attribute rol -->
			<?= $form->field($model, 'rol')->textInput(['maxlength' => true]) ?>

<!-- attribute nombre -->
			<?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

<!-- attribute apellido1 -->
			<?= $form->field($model, 'apellido1')->textInput(['maxlength' => true]) ?>

<!-- attribute apellido2 -->
			<?= $form->field($model, 'apellido2')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('models', 'Agente'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
