<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "acreditacion_estudio".
 *
 * @property integer $nk
 * @property integer $cod_ruct
 * @property string $fecha_verificacion
 * @property string $fecha_implantacion
 * @property string $fecha_acreditacion
 * @property integer $anyos_validez
 * @property string $aliasModel
 */
abstract class AcreditacionEstudio extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'acreditacion_estudio';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nk'], 'required'],
            [['nk', 'cod_ruct', 'anyos_validez'], 'integer'],
            [['fecha_verificacion', 'fecha_implantacion', 'fecha_acreditacion'], 'safe'],
            [['nk'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'nk' => Yii::t('models', 'Cód. estudio'),
            'cod_ruct' => Yii::t('models', 'Cód. RUCT'),
            'fecha_verificacion' => Yii::t('models', 'Fecha de verificación'),
            'fecha_implantacion' => Yii::t('models', 'Fecha de implantación'),
            'fecha_acreditacion' => Yii::t('models', 'Fecha de última renovación'),
            'anyos_validez' => Yii::t('models', 'Años de validez'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'nk' => Yii::t('models', 'Código del estudio'),
            'cod_ruct' => Yii::t('models', 'Código en el Registro de Universidades, Centros y Títulos'),
            'fecha_implantacion' => Yii::t('models', 'Fecha de implantación'),
            'fecha_acreditacion' => Yii::t('models', 'Fecha de última renovación de la acreditación'),
        ]);
    }




}
