<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_acreditacion_titulaciones".
 *
 * @property integer $id
 * @property double $TASA_EFICIENCIA
 * @property integer $ALUMNOS_MATRICULADOS
 * @property double $CREDITOS_RECONOCIDOS
 * @property integer $TIPO_ESTUDIO
 * @property integer $ALUMNOS_GRADUADOS
 * @property double $TASA_GRADUACION
 * @property integer $PLAZAS_OFERTADAS
 * @property double $DURACION_MEDIA_GRADUADOS
 * @property integer $ALUMNOS_ADAPTA_GRADO_TITULADO
 * @property double $TASA_ABANDONO
 * @property double $TASA_EXITO
 * @property integer $COD_CENTRO
 * @property string $DENOM_ESTUDIO
 * @property integer $ALUMNOS_NUEVO_INGRESO
 * @property integer $ALUMNOS_ADAPTA_GRADO_MATRI
 * @property double $TASA_RENDIMIENTO
 * @property string $FECHA_CARGA
 * @property integer $ALUMNOS_ADAPTA_GRADO_MATRI_NI
 * @property integer $ANO_ACADEMICO
 * @property integer $ALUMNOS_CON_RECONOCIMIENTO
 * @property integer $CREDITOS_MATRICULADOS
 * @property integer $COD_ESTUDIO
 * @property integer $ALUMNOS_MOVILIDAD_SALIDA
 * @property integer $ALUMNOS_MOVILIDAD_ENTRADA
 * @property string $aliasModel
 */
abstract class AcreditacionTitulaciones extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_acreditacion_titulaciones';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['TASA_EFICIENCIA', 'CREDITOS_RECONOCIDOS', 'TASA_GRADUACION', 'DURACION_MEDIA_GRADUADOS', 'TASA_ABANDONO', 'TASA_EXITO', 'TASA_RENDIMIENTO'], 'number'],
            [['ALUMNOS_MATRICULADOS', 'TIPO_ESTUDIO', 'ALUMNOS_GRADUADOS', 'PLAZAS_OFERTADAS', 'ALUMNOS_ADAPTA_GRADO_TITULADO', 'COD_CENTRO', 'ALUMNOS_NUEVO_INGRESO', 'ALUMNOS_ADAPTA_GRADO_MATRI', 'ALUMNOS_ADAPTA_GRADO_MATRI_NI', 'ANO_ACADEMICO', 'ALUMNOS_CON_RECONOCIMIENTO', 'CREDITOS_MATRICULADOS', 'COD_ESTUDIO', 'ALUMNOS_MOVILIDAD_SALIDA', 'ALUMNOS_MOVILIDAD_ENTRADA'], 'integer'],
            [['FECHA_CARGA'], 'safe'],
            [['DENOM_ESTUDIO'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'TASA_EFICIENCIA' => Yii::t('models', 'Tasa  Eficiencia'),
            'ALUMNOS_MATRICULADOS' => Yii::t('models', 'Alumnos  Matriculados'),
            'CREDITOS_RECONOCIDOS' => Yii::t('models', 'Creditos  Reconocidos'),
            'TIPO_ESTUDIO' => Yii::t('models', 'Tipo  Estudio'),
            'ALUMNOS_GRADUADOS' => Yii::t('models', 'Alumnos  Graduados'),
            'TASA_GRADUACION' => Yii::t('models', 'Tasa  Graduacion'),
            'PLAZAS_OFERTADAS' => Yii::t('models', 'Plazas  Ofertadas'),
            'DURACION_MEDIA_GRADUADOS' => Yii::t('models', 'Duracion  Media  Graduados'),
            'ALUMNOS_ADAPTA_GRADO_TITULADO' => Yii::t('models', 'Alumnos  Adapta  Grado  Titulado'),
            'TASA_ABANDONO' => Yii::t('models', 'Tasa  Abandono'),
            'TASA_EXITO' => Yii::t('models', 'Tasa  Exito'),
            'COD_CENTRO' => Yii::t('models', 'Cod  Centro'),
            'DENOM_ESTUDIO' => Yii::t('models', 'Denom  Estudio'),
            'ALUMNOS_NUEVO_INGRESO' => Yii::t('models', 'Alumnos  Nuevo  Ingreso'),
            'ALUMNOS_ADAPTA_GRADO_MATRI' => Yii::t('models', 'Alumnos  Adapta  Grado  Matri'),
            'TASA_RENDIMIENTO' => Yii::t('models', 'Tasa  Rendimiento'),
            'FECHA_CARGA' => Yii::t('models', 'Fecha  Carga'),
            'ALUMNOS_ADAPTA_GRADO_MATRI_NI' => Yii::t('models', 'Alumnos  Adapta  Grado  Matri  Ni'),
            'ANO_ACADEMICO' => Yii::t('models', 'Ano  Academico'),
            'ALUMNOS_CON_RECONOCIMIENTO' => Yii::t('models', 'Alumnos  Con  Reconocimiento'),
            'CREDITOS_MATRICULADOS' => Yii::t('models', 'Creditos  Matriculados'),
            'COD_ESTUDIO' => Yii::t('models', 'Cod  Estudio'),
            'ALUMNOS_MOVILIDAD_SALIDA' => Yii::t('models', 'Alumnos  Movilidad  Salida'),
            'ALUMNOS_MOVILIDAD_ENTRADA' => Yii::t('models', 'Alumnos  Movilidad  Entrada'),
        ];
    }




}
