<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "agente".
 *
 * @property integer $id
 * @property integer $centro_id
 * @property integer $plan_id_nk
 * @property integer $estudio_id
 * @property string $comision_id
 * @property string $rol
 * @property string $nombre
 * @property string $apellido1
 * @property string $apellido2
 * @property string $email
 * @property integer $nip
 * @property string $doc_id
 * @property integer $estudio_id_nk
 * @property string $aliasModel
 */
abstract class Agente extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'agente';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['centro_id', 'plan_id_nk', 'estudio_id', 'nip', 'estudio_id_nk'], 'integer'],
            [['comision_id'], 'string', 'max' => 8],
            [['rol', 'nombre', 'apellido1', 'apellido2'], 'string', 'max' => 32],
            [['email'], 'string', 'max' => 254],
            [['doc_id'], 'string', 'max' => 16]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'centro_id' => Yii::t('models', 'Centro ID'),
            'plan_id_nk' => Yii::t('models', 'Plan Id Nk'),
            'estudio_id' => Yii::t('models', 'Estudio ID'),
            'comision_id' => Yii::t('models', 'Comision ID'),
            'rol' => Yii::t('models', 'Rol'),
            'nombre' => Yii::t('models', 'Nombre'),
            'apellido1' => Yii::t('models', 'Apellido1'),
            'apellido2' => Yii::t('models', 'Apellido2'),
            'email' => Yii::t('models', 'Email'),
            'nip' => Yii::t('models', 'Nip'),
            'doc_id' => Yii::t('models', 'Doc ID'),
            'estudio_id_nk' => Yii::t('models', 'Estudio Id Nk'),
        ];
    }




}
