<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_asignatura_indicador".
 *
 * @property integer $id
 * @property integer $ANO_ACADEMICO
 * @property integer $COD_CENTRO
 * @property integer $COD_ESTUDIO
 * @property string $DENOM_ESTUDIO
 * @property string $TIPO_ESTUDIO
 * @property integer $PRELA_CU
 * @property string $COD_ASIGNATURA
 * @property string $DENOM_ASIGNATURA
 * @property integer $TOTAL_ALUMNOS
 * @property integer $ALUMNOS_RECONOCIDOS
 * @property integer $ALUMNOS_APROBADOS
 * @property integer $ALUMNOS_SUSPENDIDOS
 * @property integer $ALUMNOS_NO_PRESENTADOS
 * @property integer $CUATRIMESTRE
 * @property double $TASA_EXITO
 * @property double $TASA_RENDIMIENTO
 * @property string $A_FECHA
 * @property string $aliasModel
 */
abstract class AsignaturaIndicador extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_asignatura_indicador';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ANO_ACADEMICO', 'COD_CENTRO', 'COD_ESTUDIO', 'PRELA_CU', 'TOTAL_ALUMNOS', 'ALUMNOS_RECONOCIDOS', 'ALUMNOS_APROBADOS', 'ALUMNOS_SUSPENDIDOS', 'ALUMNOS_NO_PRESENTADOS', 'CUATRIMESTRE'], 'integer'],
            [['TASA_EXITO', 'TASA_RENDIMIENTO'], 'number'],
            [['A_FECHA'], 'safe'],
            [['DENOM_ESTUDIO', 'DENOM_ASIGNATURA'], 'string', 'max' => 255],
            [['TIPO_ESTUDIO'], 'string', 'max' => 3],
            [['COD_ASIGNATURA'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ANO_ACADEMICO' => Yii::t('models', 'Ano  Academico'),
            'COD_CENTRO' => Yii::t('models', 'Cod  Centro'),
            'COD_ESTUDIO' => Yii::t('models', 'Cod  Estudio'),
            'DENOM_ESTUDIO' => Yii::t('models', 'Denom  Estudio'),
            'TIPO_ESTUDIO' => Yii::t('models', 'Tipo  Estudio'),
            'PRELA_CU' => Yii::t('models', 'Prela  Cu'),
            'COD_ASIGNATURA' => Yii::t('models', 'Cod  Asignatura'),
            'DENOM_ASIGNATURA' => Yii::t('models', 'Denom  Asignatura'),
            'TOTAL_ALUMNOS' => Yii::t('models', 'Total  Alumnos'),
            'ALUMNOS_RECONOCIDOS' => Yii::t('models', 'Alumnos  Reconocidos'),
            'ALUMNOS_APROBADOS' => Yii::t('models', 'Alumnos  Aprobados'),
            'ALUMNOS_SUSPENDIDOS' => Yii::t('models', 'Alumnos  Suspendidos'),
            'ALUMNOS_NO_PRESENTADOS' => Yii::t('models', 'Alumnos  No  Presentados'),
            'CUATRIMESTRE' => Yii::t('models', 'Cuatrimestre'),
            'TASA_EXITO' => Yii::t('models', 'Tasa  Exito'),
            'TASA_RENDIMIENTO' => Yii::t('models', 'Tasa  Rendimiento'),
            'A_FECHA' => Yii::t('models', 'A  Fecha'),
        ];
    }




}
