<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_asignatura_calificacion".
 *
 * @property integer $id
 * @property integer $ANO_ACADEMICO
 * @property integer $COD_CENTRO
 * @property integer $COD_PLAN
 * @property integer $COD_ESTUDIO
 * @property string $DENOM_ESTUDIO
 * @property string $TIPO_ESTUDIO
 * @property integer $PRELA_CU
 * @property string $COD_ASIGNATURA
 * @property string $DENOM_ASIGNATURA
 * @property integer $ALUMNOS_APROBADOS
 * @property integer $ALUMNOS_SUSPENDIDOS
 * @property integer $ALUMNOS_NO_PRESENTADOS
 * @property integer $NUMERO_APROBADO
 * @property integer $NUMERO_NOTABLE
 * @property integer $NUMERO_SOBRESALIENTE
 * @property integer $NUMERO_MATRICULA_HONOR
 * @property integer $NUMERO_OTRO
 * @property string $A_FECHA
 * @property string $aliasModel
 */
abstract class AsignaturaCalificacion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_asignatura_calificacion';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ANO_ACADEMICO', 'COD_CENTRO', 'COD_PLAN', 'COD_ESTUDIO', 'PRELA_CU', 'ALUMNOS_APROBADOS', 'ALUMNOS_SUSPENDIDOS', 'ALUMNOS_NO_PRESENTADOS', 'NUMERO_APROBADO', 'NUMERO_NOTABLE', 'NUMERO_SOBRESALIENTE', 'NUMERO_MATRICULA_HONOR', 'NUMERO_OTRO'], 'integer'],
            [['A_FECHA'], 'safe'],
            [['DENOM_ESTUDIO', 'DENOM_ASIGNATURA'], 'string', 'max' => 255],
            [['TIPO_ESTUDIO'], 'string', 'max' => 3],
            [['COD_ASIGNATURA'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ANO_ACADEMICO' => Yii::t('models', 'Ano  Academico'),
            'COD_CENTRO' => Yii::t('models', 'Cod  Centro'),
            'COD_PLAN' => Yii::t('models', 'Cod  Plan'),
            'COD_ESTUDIO' => Yii::t('models', 'Cod  Estudio'),
            'DENOM_ESTUDIO' => Yii::t('models', 'Denom  Estudio'),
            'TIPO_ESTUDIO' => Yii::t('models', 'Tipo  Estudio'),
            'PRELA_CU' => Yii::t('models', 'Prela  Cu'),
            'COD_ASIGNATURA' => Yii::t('models', 'Cod  Asignatura'),
            'DENOM_ASIGNATURA' => Yii::t('models', 'Denom  Asignatura'),
            'ALUMNOS_APROBADOS' => Yii::t('models', 'Alumnos  Aprobados'),
            'ALUMNOS_SUSPENDIDOS' => Yii::t('models', 'Alumnos  Suspendidos'),
            'ALUMNOS_NO_PRESENTADOS' => Yii::t('models', 'Alumnos  No  Presentados'),
            'NUMERO_APROBADO' => Yii::t('models', 'Numero  Aprobado'),
            'NUMERO_NOTABLE' => Yii::t('models', 'Numero  Notable'),
            'NUMERO_SOBRESALIENTE' => Yii::t('models', 'Numero  Sobresaliente'),
            'NUMERO_MATRICULA_HONOR' => Yii::t('models', 'Numero  Matricula  Honor'),
            'NUMERO_OTRO' => Yii::t('models', 'Numero  Otro'),
            'A_FECHA' => Yii::t('models', 'A  Fecha'),
        ];
    }




}
