<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "asignatura_ficha".
 *
 * @property integer $id
 * @property integer $anyo_academico
 * @property integer $asignatura_id
 * @property string $language
 * @property string $aliasModel
 */
abstract class AsignaturaFicha extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'asignatura_ficha';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['anyo_academico', 'asignatura_id'], 'integer'],
            [['language'], 'string', 'max' => 5]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'anyo_academico' => Yii::t('models', 'Anyo Academico'),
            'asignatura_id' => Yii::t('models', 'Asignatura ID'),
            'language' => Yii::t('models', 'Language'),
        ];
    }




}
