<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "calendario".
 *
 * @property integer $id
 * @property integer $anyo
 * @property string $evento
 * @property string $fecha
 * @property string $aliasModel
 */
abstract class Calendario extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'calendario';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['anyo'], 'integer'],
            [['fecha'], 'safe'],
            [['evento'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'anyo' => Yii::t('models', 'Anyo'),
            'evento' => Yii::t('models', 'Evento'),
            'fecha' => Yii::t('models', 'Fecha'),
        ];
    }




}
