<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "centro_lang".
 *
 * @property integer $id
 * @property integer $centro_id
 * @property string $language
 * @property string $nombre
 *
 * @property \app\models\Centro $centro
 * @property string $aliasModel
 */
abstract class CentroLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'centro_lang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['centro_id'], 'required'],
            [['centro_id'], 'integer'],
            [['language'], 'string', 'max' => 5],
            [['nombre'], 'string', 'max' => 255],
            [['centro_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Centro::className(), 'targetAttribute' => ['centro_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'centro_id' => Yii::t('models', 'Centro ID'),
            'language' => Yii::t('models', 'Language'),
            'nombre' => Yii::t('models', 'Nombre'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCentro()
    {
        return $this->hasOne(\app\models\Centro::className(), ['id' => 'centro_id']);
    }




}
