<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use dosamigos\translateable\TranslateableBehavior;

/**
 * This is the base-model class for table "centro".
 *
 * @property integer $id
 * @property string $rrhh_id_nk
 * @property integer $activo
 * @property string $tipo_centro
 * @property string $direccion
 * @property string $municipio
 * @property string $telefono
 * @property string $url
 * @property integer $nip_decano
 * @property string $nombre_decano
 * @property string $email_decano
 * @property string $tratamiento_decano
 * @property integer $nip_administrador
 * @property string $nombre_administrador
 * @property string $email_administrador
 * @property string $acreditacion_url
 * @property string $fecha_acreditacion
 * @property integer $anyos_validez
 *
 * @property \app\models\CentroHistorico[] $centroHistoricos
 * @property \app\models\Plan[] $plans
 * @property string $aliasModel
 */
abstract class Centro extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'centro';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'translatable' => [
                'class' => TranslateableBehavior::className(),
                // in case you renamed your relation, you can setup its name
                // 'relation' => 'translations',
                'translationAttributes' => [
                    'nombre'
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['activo', 'nip_decano', 'nip_administrador', 'anyos_validez'], 'integer'],
            [['fecha_acreditacion'], 'safe'],
            [['rrhh_id_nk'], 'string', 'max' => 4],
            [['tipo_centro', 'telefono'], 'string', 'max' => 30],
            [['direccion'], 'string', 'max' => 140],
            [['municipio'], 'string', 'max' => 50],
            [['url'], 'string', 'max' => 80],
            [['nombre_decano'], 'string', 'max' => 128],
            [['email_decano', 'tratamiento_decano', 'email_administrador'], 'string', 'max' => 254],
            [['nombre_administrador', 'acreditacion_url'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'rrhh_id_nk' => Yii::t('models', 'Rrhh Id Nk'),
            'activo' => Yii::t('models', 'Activo'),
            'tipo_centro' => Yii::t('models', 'Tipo Centro'),
            'direccion' => Yii::t('models', 'Direccion'),
            'municipio' => Yii::t('models', 'Municipio'),
            'telefono' => Yii::t('models', 'Telefono'),
            'url' => Yii::t('models', 'Url'),
            'nip_decano' => Yii::t('models', 'Nip Decano'),
            'nombre_decano' => Yii::t('models', 'Nombre Decano'),
            'email_decano' => Yii::t('models', 'Email Decano'),
            'tratamiento_decano' => Yii::t('models', 'Tratamiento Decano'),
            'nip_administrador' => Yii::t('models', 'Nip Administrador'),
            'nombre_administrador' => Yii::t('models', 'Nombre Administrador'),
            'email_administrador' => Yii::t('models', 'Email Administrador'),
            'acreditacion_url' => Yii::t('models', 'Acreditacion Url'),
            'fecha_acreditacion' => Yii::t('models', 'Fecha Acreditacion'),
            'anyos_validez' => Yii::t('models', 'Anyos Validez'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'nip_decano' => Yii::t('models', 'NIP del decano/director'),
            'tratamiento_decano' => Yii::t('models', 'Decano/Director'),
            'nip_administrador' => Yii::t('models', 'NIP del administrador del centro'),
            'acreditacion_url' => Yii::t('models', 'URL de la acreditación institucional del centro'),
            'fecha_acreditacion' => Yii::t('models', 'Fecha de acreditación institucional'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCentroHistoricos()
    {
        return $this->hasMany(\app\models\CentroHistorico::className(), ['centro_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlans()
    {
        return $this->hasMany(\app\models\Plan::className(), ['centro_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        return $this->hasMany(\app\models\CentroLang::className(), ['centro_id' => 'id']);
    }



}
