<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_CIFICE".
 *
 * @property integer $id
 * @property integer $cod_centro
 * @property integer $cod_estudio
 * @property string $denom_estudio
 * @property integer $cursos_cifice
 * @property integer $participantes_cifice
 * @property integer $ano_academico
 * @property string $aliasModel
 */
abstract class Cifice extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_CIFICE';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cod_centro', 'cod_estudio', 'cursos_cifice', 'participantes_cifice', 'ano_academico'], 'integer'],
            [['denom_estudio'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'cod_centro' => Yii::t('models', 'Cod Centro'),
            'cod_estudio' => Yii::t('models', 'Cod Estudio'),
            'denom_estudio' => Yii::t('models', 'Denom Estudio'),
            'cursos_cifice' => Yii::t('models', 'Cursos Cifice'),
            'participantes_cifice' => Yii::t('models', 'Participantes Cifice'),
            'ano_academico' => Yii::t('models', 'Ano Academico'),
        ];
    }




}
