<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_doctorado".
 *
 * @property integer $id
 * @property integer $cod_estudio
 * @property integer $cod_plan
 * @property integer $cod_centro
 * @property integer $ano_academico
 * @property integer $plazas_ofertadas
 * @property integer $num_solicitudes
 * @property integer $alumnos_nuevo_ingreso
 * @property double $porc_est_previo_nouz
 * @property double $porc_ni_comp_formacion
 * @property double $porc_ni_tiempo_parcial
 * @property integer $alumnos_ni_tiempo_parcial
 * @property integer $alumnos_matriculados
 * @property double $porc_matr_extrajeros
 * @property double $porc_alumnos_beca
 * @property double $porc_alumnos_beca_distinta
 * @property double $porc_matri_tiempo_parcial
 * @property integer $alumnos_act_transv
 * @property integer $cursos_act_transv
 * @property double $porc_alumnos_mov_out_ano
 * @property double $porc_alumnos_mov_out_gen
 * @property integer $numero_profesores
 * @property integer $numero_profesores_uz
 * @property integer $numero_profesores_nouz
 * @property integer $num_sexenios_profesores
 * @property double $porc_sexenios_vivos
 * @property double $porc_prof_tiempo_completo
 * @property integer $numero_expertos_int_trib
 * @property integer $numero_miembros_trib
 * @property integer $numero_directores_tesis_leidas
 * @property double $porc_dir_tes_le_sexenios_vivos
 * @property integer $numero_proy_inter_vivos
 * @property integer $numero_proy_nac_vivos
 * @property double $numero_publ_indexadas
 * @property double $numero_publ_no_indexadas
 * @property integer $numero_tesis_tiempo_completo
 * @property integer $numero_tesis_tiempo_parcial
 * @property double $duracion_media_tiempo_completo
 * @property double $duracion_media_tiempo_parcial
 * @property double $porc_abandono
 * @property double $porc_tesis_no_pri_prorroga
 * @property double $porc_tesis_no_seg_prorroga
 * @property double $porc_tesis_cum_laude
 * @property double $porc_tesis_men_internacional
 * @property double $porc_tesis_men_doc_industrial
 * @property double $porc_tesis_cotutela
 * @property double $num_medio_resultados_tesis
 * @property integer $numero_alu_encuesta_global_1
 * @property integer $numero_alu_encuesta_global_2
 * @property integer $numero_alu_encuesta_global_3
 * @property integer $numero_alu_encuesta_global_4
 * @property integer $numero_alu_encuesta_global_5
 * @property integer $numero_prof_encuesta_global_1
 * @property integer $numero_prof_encuesta_global_2
 * @property integer $numero_prof_encuesta_global_3
 * @property integer $numero_prof_encuesta_global_4
 * @property integer $numero_prof_encuesta_global_5
 * @property string $fecha_carga
 * @property string $aliasModel
 */
abstract class Doctorado extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_doctorado';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cod_estudio', 'cod_plan', 'cod_centro', 'ano_academico', 'plazas_ofertadas', 'num_solicitudes', 'alumnos_nuevo_ingreso', 'alumnos_ni_tiempo_parcial', 'alumnos_matriculados', 'alumnos_act_transv', 'cursos_act_transv', 'numero_profesores', 'numero_profesores_uz', 'numero_profesores_nouz', 'num_sexenios_profesores', 'numero_expertos_int_trib', 'numero_miembros_trib', 'numero_directores_tesis_leidas', 'numero_proy_inter_vivos', 'numero_proy_nac_vivos', 'numero_tesis_tiempo_completo', 'numero_tesis_tiempo_parcial', 'numero_alu_encuesta_global_1', 'numero_alu_encuesta_global_2', 'numero_alu_encuesta_global_3', 'numero_alu_encuesta_global_4', 'numero_alu_encuesta_global_5', 'numero_prof_encuesta_global_1', 'numero_prof_encuesta_global_2', 'numero_prof_encuesta_global_3', 'numero_prof_encuesta_global_4', 'numero_prof_encuesta_global_5'], 'integer'],
            [['porc_est_previo_nouz', 'porc_ni_comp_formacion', 'porc_ni_tiempo_parcial', 'porc_matr_extrajeros', 'porc_alumnos_beca', 'porc_alumnos_beca_distinta', 'porc_matri_tiempo_parcial', 'porc_alumnos_mov_out_ano', 'porc_alumnos_mov_out_gen', 'porc_sexenios_vivos', 'porc_prof_tiempo_completo', 'porc_dir_tes_le_sexenios_vivos', 'numero_publ_indexadas', 'numero_publ_no_indexadas', 'duracion_media_tiempo_completo', 'duracion_media_tiempo_parcial', 'porc_abandono', 'porc_tesis_no_pri_prorroga', 'porc_tesis_no_seg_prorroga', 'porc_tesis_cum_laude', 'porc_tesis_men_internacional', 'porc_tesis_men_doc_industrial', 'porc_tesis_cotutela', 'num_medio_resultados_tesis'], 'number'],
            [['fecha_carga'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'cod_estudio' => Yii::t('models', 'Cod Estudio'),
            'cod_plan' => Yii::t('models', 'Cod Plan'),
            'cod_centro' => Yii::t('models', 'Cod Centro'),
            'ano_academico' => Yii::t('models', 'Ano Academico'),
            'plazas_ofertadas' => Yii::t('models', 'Plazas Ofertadas'),
            'num_solicitudes' => Yii::t('models', 'Num Solicitudes'),
            'alumnos_nuevo_ingreso' => Yii::t('models', 'Alumnos Nuevo Ingreso'),
            'porc_est_previo_nouz' => Yii::t('models', 'Porc Est Previo Nouz'),
            'porc_ni_comp_formacion' => Yii::t('models', 'Porc Ni Comp Formacion'),
            'porc_ni_tiempo_parcial' => Yii::t('models', 'Porc Ni Tiempo Parcial'),
            'alumnos_ni_tiempo_parcial' => Yii::t('models', 'Alumnos Ni Tiempo Parcial'),
            'alumnos_matriculados' => Yii::t('models', 'Alumnos Matriculados'),
            'porc_matr_extrajeros' => Yii::t('models', 'Porc Matr Extrajeros'),
            'porc_alumnos_beca' => Yii::t('models', 'Porc Alumnos Beca'),
            'porc_alumnos_beca_distinta' => Yii::t('models', 'Porc Alumnos Beca Distinta'),
            'porc_matri_tiempo_parcial' => Yii::t('models', 'Porc Matri Tiempo Parcial'),
            'alumnos_act_transv' => Yii::t('models', 'Alumnos Act Transv'),
            'cursos_act_transv' => Yii::t('models', '2.3.2. Actividades transversales de la EDUZ: cursos'),
            'porc_alumnos_mov_out_ano' => Yii::t('models', 'Porc Alumnos Mov Out Ano'),
            'porc_alumnos_mov_out_gen' => Yii::t('models', 'Porc Alumnos Mov Out Gen'),
            'numero_profesores' => Yii::t('models', 'Numero Profesores'),
            'numero_profesores_uz' => Yii::t('models', 'Numero Profesores Uz'),
            'numero_profesores_nouz' => Yii::t('models', 'Numero Profesores Nouz'),
            'num_sexenios_profesores' => Yii::t('models', 'Num Sexenios Profesores'),
            'porc_sexenios_vivos' => Yii::t('models', 'Porc Sexenios Vivos'),
            'porc_prof_tiempo_completo' => Yii::t('models', 'Porc Prof Tiempo Completo'),
            'numero_expertos_int_trib' => Yii::t('models', 'Numero Expertos Int Trib'),
            'numero_miembros_trib' => Yii::t('models', 'Numero Miembros Trib'),
            'numero_directores_tesis_leidas' => Yii::t('models', 'Numero Directores Tesis Leidas'),
            'porc_dir_tes_le_sexenios_vivos' => Yii::t('models', 'Porc Dir Tes Le Sexenios Vivos'),
            'numero_proy_inter_vivos' => Yii::t('models', 'Numero Proy Inter Vivos'),
            'numero_proy_nac_vivos' => Yii::t('models', 'Numero Proy Nac Vivos'),
            'numero_publ_indexadas' => Yii::t('models', 'Numero Publ Indexadas'),
            'numero_publ_no_indexadas' => Yii::t('models', 'Numero Publ No Indexadas'),
            'numero_tesis_tiempo_completo' => Yii::t('models', 'Numero Tesis Tiempo Completo'),
            'numero_tesis_tiempo_parcial' => Yii::t('models', 'Numero Tesis Tiempo Parcial'),
            'duracion_media_tiempo_completo' => Yii::t('models', 'Duracion Media Tiempo Completo'),
            'duracion_media_tiempo_parcial' => Yii::t('models', 'Duracion Media Tiempo Parcial'),
            'porc_abandono' => Yii::t('models', 'Porc Abandono'),
            'porc_tesis_no_pri_prorroga' => Yii::t('models', 'Porc Tesis No Pri Prorroga'),
            'porc_tesis_no_seg_prorroga' => Yii::t('models', 'Porc Tesis No Seg Prorroga'),
            'porc_tesis_cum_laude' => Yii::t('models', 'Porc Tesis Cum Laude'),
            'porc_tesis_men_internacional' => Yii::t('models', 'Porc Tesis Men Internacional'),
            'porc_tesis_men_doc_industrial' => Yii::t('models', 'Porc Tesis Men Doc Industrial'),
            'porc_tesis_cotutela' => Yii::t('models', 'Porc Tesis Cotutela'),
            'num_medio_resultados_tesis' => Yii::t('models', 'Num Medio Resultados Tesis'),
            'numero_alu_encuesta_global_1' => Yii::t('models', 'Numero Alu Encuesta Global 1'),
            'numero_alu_encuesta_global_2' => Yii::t('models', 'Numero Alu Encuesta Global 2'),
            'numero_alu_encuesta_global_3' => Yii::t('models', 'Numero Alu Encuesta Global 3'),
            'numero_alu_encuesta_global_4' => Yii::t('models', 'Numero Alu Encuesta Global 4'),
            'numero_alu_encuesta_global_5' => Yii::t('models', 'Numero Alu Encuesta Global 5'),
            'numero_prof_encuesta_global_1' => Yii::t('models', 'Numero Prof Encuesta Global 1'),
            'numero_prof_encuesta_global_2' => Yii::t('models', 'Numero Prof Encuesta Global 2'),
            'numero_prof_encuesta_global_3' => Yii::t('models', 'Numero Prof Encuesta Global 3'),
            'numero_prof_encuesta_global_4' => Yii::t('models', 'Numero Prof Encuesta Global 4'),
            'numero_prof_encuesta_global_5' => Yii::t('models', 'Numero Prof Encuesta Global 5'),
            'fecha_carga' => Yii::t('models', 'Fecha Carga'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'cursos_act_transv' => Yii::t('models', '2.3.2. Actividades transversales de la EDUZ: cursos'),
        ]);
    }




}
