<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_doctorado_macroarea".
 *
 * @property integer $id
 * @property string $cod_rama_conocimiento
 * @property integer $ano_academico
 * @property integer $plazas_ofertadas
 * @property integer $num_solicitudes
 * @property integer $alumnos_nuevo_ingreso
 * @property double $porc_est_previo_nouz
 * @property double $porc_ni_comp_formacion
 * @property double $porc_ni_tiempo_parcial
 * @property integer $alumnos_matriculados
 * @property double $porc_matr_extrajeros
 * @property double $porc_alumnos_beca
 * @property double $porc_alumnos_beca_distinta
 * @property double $porc_matri_tiempo_parcial
 * @property integer $alumnos_act_transv
 * @property integer $cursos_act_transv
 * @property integer $numero_tesis_tiempo_completo
 * @property integer $numero_tesis_tiempo_parcial
 * @property double $duracion_media_tiempo_completo
 * @property double $duracion_media_tiempo_parcial
 * @property double $porc_abandono
 * @property double $porc_tesis_no_pri_prorroga
 * @property double $porc_tesis_no_seg_prorroga
 * @property double $porc_tesis_cum_laude
 * @property double $porc_tesis_men_internacional
 * @property double $porc_tesis_men_doc_industrial
 * @property double $porc_tesis_cotutela
 * @property double $num_medio_resultados_tesis
 * @property double $porc_alumnos_mov_out_ano
 * @property double $porc_alumnos_mov_out_gen
 * @property integer $numero_profesores
 * @property integer $numero_profesores_uz
 * @property integer $numero_profesores_nouz
 * @property integer $num_sexenios_profesores
 * @property double $porc_sexenios_vivos
 * @property double $porc_prof_tiempo_completo
 * @property integer $numero_expertos_int_trib
 * @property integer $numero_miembros_trib
 * @property integer $numero_directores_tesis_leidas
 * @property double $porc_dir_tes_le_sexenios_vivos
 * @property integer $numero_proy_inter_vivos
 * @property integer $numero_proy_nac_vivos
 * @property double $numero_publ_indexadas
 * @property double $numero_publ_no_indexadas
 * @property double $tasa_satisfaccion_estudiantes
 * @property double $media_satisfaccion_estudiantes
 * @property double $tasa_satisfaccion_tutores
 * @property double $media_satisfaccion_tutores
 * @property double $tasa_satisfaccion_egresados
 * @property double $media_satisfaccion_egresados
 * @property string $fecha_carga
 * @property integer $num_programas
 * @property string $aliasModel
 */
abstract class DoctoradoMacroarea extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_doctorado_macroarea';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ano_academico', 'plazas_ofertadas', 'num_solicitudes', 'alumnos_nuevo_ingreso', 'alumnos_matriculados', 'alumnos_act_transv', 'cursos_act_transv', 'numero_tesis_tiempo_completo', 'numero_tesis_tiempo_parcial', 'numero_profesores', 'numero_profesores_uz', 'numero_profesores_nouz', 'num_sexenios_profesores', 'numero_expertos_int_trib', 'numero_miembros_trib', 'numero_directores_tesis_leidas', 'numero_proy_inter_vivos', 'numero_proy_nac_vivos', 'num_programas'], 'integer'],
            [['porc_est_previo_nouz', 'porc_ni_comp_formacion', 'porc_ni_tiempo_parcial', 'porc_matr_extrajeros', 'porc_alumnos_beca', 'porc_alumnos_beca_distinta', 'porc_matri_tiempo_parcial', 'duracion_media_tiempo_completo', 'duracion_media_tiempo_parcial', 'porc_abandono', 'porc_tesis_no_pri_prorroga', 'porc_tesis_no_seg_prorroga', 'porc_tesis_cum_laude', 'porc_tesis_men_internacional', 'porc_tesis_men_doc_industrial', 'porc_tesis_cotutela', 'num_medio_resultados_tesis', 'porc_alumnos_mov_out_ano', 'porc_alumnos_mov_out_gen', 'porc_sexenios_vivos', 'porc_prof_tiempo_completo', 'porc_dir_tes_le_sexenios_vivos', 'numero_publ_indexadas', 'numero_publ_no_indexadas', 'tasa_satisfaccion_estudiantes', 'media_satisfaccion_estudiantes', 'tasa_satisfaccion_tutores', 'media_satisfaccion_tutores', 'tasa_satisfaccion_egresados', 'media_satisfaccion_egresados'], 'number'],
            [['fecha_carga'], 'safe'],
            [['cod_rama_conocimiento'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'cod_rama_conocimiento' => Yii::t('models', 'Cod Rama Conocimiento'),
            'ano_academico' => Yii::t('models', 'Ano Academico'),
            'plazas_ofertadas' => Yii::t('models', 'Plazas Ofertadas'),
            'num_solicitudes' => Yii::t('models', 'Num Solicitudes'),
            'alumnos_nuevo_ingreso' => Yii::t('models', 'Alumnos Nuevo Ingreso'),
            'porc_est_previo_nouz' => Yii::t('models', 'Porc Est Previo Nouz'),
            'porc_ni_comp_formacion' => Yii::t('models', 'Porc Ni Comp Formacion'),
            'porc_ni_tiempo_parcial' => Yii::t('models', 'Porc Ni Tiempo Parcial'),
            'alumnos_matriculados' => Yii::t('models', 'Alumnos Matriculados'),
            'porc_matr_extrajeros' => Yii::t('models', 'Porc Matr Extrajeros'),
            'porc_alumnos_beca' => Yii::t('models', 'Porc Alumnos Beca'),
            'porc_alumnos_beca_distinta' => Yii::t('models', 'Porc Alumnos Beca Distinta'),
            'porc_matri_tiempo_parcial' => Yii::t('models', 'Porc Matri Tiempo Parcial'),
            'alumnos_act_transv' => Yii::t('models', 'Alumnos Act Transv'),
            'cursos_act_transv' => Yii::t('models', '2.3.2. Actividades transversales de la EDUZ: cursos'),
            'numero_tesis_tiempo_completo' => Yii::t('models', 'Numero Tesis Tiempo Completo'),
            'numero_tesis_tiempo_parcial' => Yii::t('models', 'Numero Tesis Tiempo Parcial'),
            'duracion_media_tiempo_completo' => Yii::t('models', 'Duracion Media Tiempo Completo'),
            'duracion_media_tiempo_parcial' => Yii::t('models', 'Duracion Media Tiempo Parcial'),
            'porc_abandono' => Yii::t('models', 'Porc Abandono'),
            'porc_tesis_no_pri_prorroga' => Yii::t('models', 'Porc Tesis No Pri Prorroga'),
            'porc_tesis_no_seg_prorroga' => Yii::t('models', 'Porc Tesis No Seg Prorroga'),
            'porc_tesis_cum_laude' => Yii::t('models', 'Porc Tesis Cum Laude'),
            'porc_tesis_men_internacional' => Yii::t('models', 'Porc Tesis Men Internacional'),
            'porc_tesis_men_doc_industrial' => Yii::t('models', 'Porc Tesis Men Doc Industrial'),
            'porc_tesis_cotutela' => Yii::t('models', 'Porc Tesis Cotutela'),
            'num_medio_resultados_tesis' => Yii::t('models', 'Num Medio Resultados Tesis'),
            'porc_alumnos_mov_out_ano' => Yii::t('models', '3.1. Porcentaje de estudiantes del PD a los que se le autoriza realizar estancias internacionales de investigación en el curso académico objeto del informe.'),
            'porc_alumnos_mov_out_gen' => Yii::t('models', '3.2. Porcentaje de estudiantes del programa de doctorado que han realizado estancias de investigación'),
            'numero_profesores' => Yii::t('models', '4.1. Número total de directores y tutores de tesis'),
            'numero_profesores_uz' => Yii::t('models', '4.1.1. Número total de directores y tutores con vinculación contractual con la Universidad de Zaragoza'),
            'numero_profesores_nouz' => Yii::t('models', '4.1.2. Número total de directores y tutores sin vinculación contractual con la Universidad de Zaragoza'),
            'num_sexenios_profesores' => Yii::t('models', '4.2. Experiencia investigadora'),
            'porc_sexenios_vivos' => Yii::t('models', '4.3. Porcentaje de sexenios vivos'),
            'porc_prof_tiempo_completo' => Yii::t('models', '4.4. Porcentaje de dedicación'),
            'numero_expertos_int_trib' => Yii::t('models', '4.5. Numerador: Número de miembros internacionales en los tribunales'),
            'numero_miembros_trib' => Yii::t('models', '4.5. Denominador: Número de miembros tribunales de tesis defendidas en el curso objeto del estudio'),
            'numero_directores_tesis_leidas' => Yii::t('models', '4.6. Número de directores de tesis leídas'),
            'porc_dir_tes_le_sexenios_vivos' => Yii::t('models', '4.7. Sexenios vivos de los directores de tesis leídas'),
            'numero_proy_inter_vivos' => Yii::t('models', '4.8. Número de proyectos internacionales vivos en el año'),
            'numero_proy_nac_vivos' => Yii::t('models', '4.9. Número de proyectos nacionales vivos en el año'),
            'numero_publ_indexadas' => Yii::t('models', '4.10. Número de publicaciones indexadas en el año'),
            'numero_publ_no_indexadas' => Yii::t('models', '4.11. Número de publicaciones no indexadas en el año'),
            'tasa_satisfaccion_estudiantes' => Yii::t('models', 'Tasa de respuesta de satisfacción de los estudiantes con el programa'),
            'media_satisfaccion_estudiantes' => Yii::t('models', 'Media de satisfacción de los estudiantes con el programa'),
            'tasa_satisfaccion_tutores' => Yii::t('models', 'Tasa de respuesta de satisfacción de los directores/tutores con el programa'),
            'media_satisfaccion_tutores' => Yii::t('models', 'Media de satisfacción de los directores/tutores con el programa'),
            'tasa_satisfaccion_egresados' => Yii::t('models', 'Tasa de respuesta de satisfacción de los egresados con el programa'),
            'media_satisfaccion_egresados' => Yii::t('models', 'Media de satisfacción de los egresados con el programa'),
            'fecha_carga' => Yii::t('models', 'Fecha Carga'),
            'num_programas' => Yii::t('models', 'Num Programas'),
        ];
    }




}
