<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_encuestas".
 *
 * @property integer $ID_CENTRO_DOCENTE_NK
 * @property integer $ID_CURSO_ACADEMICO_NK
 * @property integer $ID_PLAN_ESTUDIO_NK
 * @property integer $ID_ENCUESTA_NK
 * @property string $NOMBRE_PLAN_ESTUDIO
 * @property double $PORC_RESPUESTA_PLAN
 * @property double $MEDIA_PLAN
 * @property string $NOMBRE_ENCUESTA
 * @property integer $ID_TIPO_ESTUDIO_NK
 * @property string $aliasModel
 */
abstract class Encuestas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_encuestas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID_CENTRO_DOCENTE_NK', 'ID_CURSO_ACADEMICO_NK', 'ID_PLAN_ESTUDIO_NK', 'ID_ENCUESTA_NK', 'ID_TIPO_ESTUDIO_NK'], 'integer'],
            [['NOMBRE_PLAN_ESTUDIO', 'NOMBRE_ENCUESTA'], 'string'],
            [['PORC_RESPUESTA_PLAN', 'MEDIA_PLAN'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID_CENTRO_DOCENTE_NK' => Yii::t('models', 'Id  Centro  Docente  Nk'),
            'ID_CURSO_ACADEMICO_NK' => Yii::t('models', 'Id  Curso  Academico  Nk'),
            'ID_PLAN_ESTUDIO_NK' => Yii::t('models', 'Id  Plan  Estudio  Nk'),
            'ID_ENCUESTA_NK' => Yii::t('models', 'Id  Encuesta  Nk'),
            'NOMBRE_PLAN_ESTUDIO' => Yii::t('models', 'Nombre  Plan  Estudio'),
            'PORC_RESPUESTA_PLAN' => Yii::t('models', 'Porc  Respuesta  Plan'),
            'MEDIA_PLAN' => Yii::t('models', 'Media  Plan'),
            'NOMBRE_ENCUESTA' => Yii::t('models', 'Nombre  Encuesta'),
            'ID_TIPO_ESTUDIO_NK' => Yii::t('models', 'Id  Tipo  Estudio  Nk'),
        ];
    }




}
