<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "enlace_lang".
 *
 * @property integer $id
 * @property integer $enlace_id
 * @property string $language
 * @property string $nombre
 *
 * @property \app\models\Enlace $enlace
 * @property string $aliasModel
 */
abstract class EnlaceLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'enlace_lang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['enlace_id'], 'integer'],
            [['language'], 'string', 'max' => 5],
            [['nombre'], 'string', 'max' => 255],
            [['enlace_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Enlace::className(), 'targetAttribute' => ['enlace_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'enlace_id' => Yii::t('models', 'Enlace ID'),
            'language' => Yii::t('models', 'Language'),
            'nombre' => Yii::t('models', 'Nombre'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEnlace()
    {
        return $this->hasOne(\app\models\Enlace::className(), ['id' => 'enlace_id']);
    }




}
