<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "estudio_lang".
 *
 * @property integer $id
 * @property integer $estudio_id
 * @property string $language
 * @property string $nombre
 * @property integer $anyo_academico
 * @property integer $estudio_id_nk
 *
 * @property \app\models\Estudio $estudio
 * @property string $aliasModel
 */
abstract class EstudioLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'estudio_lang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['estudio_id', 'anyo_academico', 'estudio_id_nk'], 'integer'],
            [['language'], 'string', 'max' => 5],
            [['nombre'], 'string', 'max' => 255],
            [['estudio_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Estudio::className(), 'targetAttribute' => ['estudio_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'estudio_id' => Yii::t('models', 'Estudio ID'),
            'language' => Yii::t('models', 'Language'),
            'nombre' => Yii::t('models', 'Nombre'),
            'anyo_academico' => Yii::t('models', 'Anyo Academico'),
            'estudio_id_nk' => Yii::t('models', 'Estudio Id Nk'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudio()
    {
        return $this->hasOne(\app\models\Estudio::className(), ['id' => 'estudio_id']);
    }




}
