<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "informacion_lang".
 *
 * @property integer $id
 * @property integer $informacion_id
 * @property string $language
 * @property string $texto
 *
 * @property \app\models\Informacion $informacion
 * @property string $aliasModel
 */
abstract class InformacionLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'informacion_lang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['informacion_id'], 'integer'],
            [['texto'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['informacion_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Informacion::className(), 'targetAttribute' => ['informacion_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'informacion_id' => Yii::t('models', 'Informacion ID'),
            'language' => Yii::t('models', 'Language'),
            'texto' => Yii::t('models', 'Texto'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInformacion()
    {
        return $this->hasOne(\app\models\Informacion::className(), ['id' => 'informacion_id']);
    }




}
