<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "informe_respuesta_lang".
 *
 * @property integer $id
 * @property integer $informe_respuesta_id
 * @property string $language
 * @property string $contenido
 *
 * @property \app\models\InformeRespuesta $informeRespuesta
 * @property string $aliasModel
 */
abstract class InformeRespuestaLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'informe_respuesta_lang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['informe_respuesta_id'], 'required'],
            [['informe_respuesta_id'], 'integer'],
            [['contenido'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['informe_respuesta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\InformeRespuesta::className(), 'targetAttribute' => ['informe_respuesta_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'informe_respuesta_id' => Yii::t('models', 'Informe Respuesta ID'),
            'language' => Yii::t('models', 'Language'),
            'contenido' => Yii::t('models', 'Contenido'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInformeRespuesta()
    {
        return $this->hasOne(\app\models\InformeRespuesta::className(), ['id' => 'informe_respuesta_id']);
    }




}
