<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "informe_pregunta_lang".
 *
 * @property integer $id
 * @property integer $informe_pregunta_id
 * @property string $language
 * @property string $titulo
 * @property string $info
 * @property string $explicacion
 * @property string $texto_comun
 *
 * @property \app\models\InformePregunta $informePregunta
 * @property string $aliasModel
 */
abstract class InformePreguntaLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'informe_pregunta_lang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['informe_pregunta_id'], 'required'],
            [['informe_pregunta_id'], 'integer'],
            [['info', 'explicacion', 'texto_comun'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['titulo'], 'string', 'max' => 511],
            [['informe_pregunta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\InformePregunta::className(), 'targetAttribute' => ['informe_pregunta_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'informe_pregunta_id' => Yii::t('models', 'Informe Pregunta ID'),
            'language' => Yii::t('models', 'Language'),
            'titulo' => Yii::t('models', 'Titulo'),
            'info' => Yii::t('models', 'Info'),
            'explicacion' => Yii::t('models', 'Explicacion'),
            'texto_comun' => Yii::t('models', 'Texto Comun'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInformePregunta()
    {
        return $this->hasOne(\app\models\InformePregunta::className(), ['id' => 'informe_pregunta_id']);
    }




}
