<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use dosamigos\translateable\TranslateableBehavior;

/**
 * This is the base-model class for table "informe_respuesta".
 *
 * @property integer $id
 * @property integer $estudio_id
 * @property integer $anyo
 * @property integer $informe_pregunta_id
 *
 * @property \app\models\Estudio $estudio
 * @property \app\models\InformePregunta $informePregunta
 * @property string $aliasModel
 */
abstract class InformeRespuesta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'informe_respuesta';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'translatable' => [
                'class' => TranslateableBehavior::className(),
                // in case you renamed your relation, you can setup its name
                // 'relation' => 'translations',
                'translationAttributes' => [
                    'contenido'
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['estudio_id', 'informe_pregunta_id'], 'required'],
            [['estudio_id', 'anyo', 'informe_pregunta_id'], 'integer'],
            [['estudio_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Estudio::className(), 'targetAttribute' => ['estudio_id' => 'id']],
            [['informe_pregunta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\InformePregunta::className(), 'targetAttribute' => ['informe_pregunta_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'estudio_id' => Yii::t('models', 'Estudio ID'),
            'anyo' => Yii::t('models', 'Anyo'),
            'informe_pregunta_id' => Yii::t('models', 'Informe Pregunta ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudio()
    {
        return $this->hasOne(\app\models\Estudio::className(), ['id' => 'estudio_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInformePregunta()
    {
        return $this->hasOne(\app\models\InformePregunta::className(), ['id' => 'informe_pregunta_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        return $this->hasMany(\app\models\InformeRespuestaLang::className(), ['informe_respuesta_id' => 'id']);
    }



}
