<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "linea_lang".
 *
 * @property integer $id
 * @property integer $linea_id
 * @property string $language
 * @property string $descripcion
 *
 * @property \app\models\Linea $linea
 * @property string $aliasModel
 */
abstract class LineaLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'linea_lang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['linea_id'], 'integer'],
            [['descripcion'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['linea_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Linea::className(), 'targetAttribute' => ['linea_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'linea_id' => Yii::t('models', 'Linea ID'),
            'language' => Yii::t('models', 'Language'),
            'descripcion' => Yii::t('models', 'Descripcion'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLinea()
    {
        return $this->hasOne(\app\models\Linea::className(), ['id' => 'linea_id']);
    }




}
