<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_movilidad".
 *
 * @property integer $id
 * @property integer $ANO_ACADEMICO
 * @property integer $COD_CENTRO
 * @property integer $COD_ESTUDIO
 * @property integer $IN_SICUE
 * @property integer $IN_ERASMUS
 * @property integer $IN_MOVILIDAD_VIRTUAL_UNITA
 * @property integer $IN_MOVILIDAD_RURAL_UNITA
 * @property integer $IN_MOVILIDAD_IBEROAMERICANA
 * @property integer $IN_NOA
 * @property integer $IN_OTROS
 * @property integer $IN_TOTAL
 * @property integer $OUT_SICUE
 * @property integer $OUT_ERASMUS
 * @property integer $OUT_MOVILIDAD_VIRTUAL_UNITA
 * @property integer $OUT_MOVILIDAD_IBEROAMERICANA
 * @property integer $OUT_NOA
 * @property integer $OUT_OTROS
 * @property integer $OUT_TOTAL
 * @property integer $ALUMNOS_TIT_OUT
 * @property double $P_TITULADOS_OUT
 * @property string $aliasModel
 */
abstract class Movilidad extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_movilidad';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ANO_ACADEMICO', 'COD_CENTRO', 'COD_ESTUDIO', 'IN_SICUE', 'IN_ERASMUS', 'IN_MOVILIDAD_VIRTUAL_UNITA', 'IN_MOVILIDAD_RURAL_UNITA', 'IN_MOVILIDAD_IBEROAMERICANA', 'IN_NOA', 'IN_OTROS', 'IN_TOTAL', 'OUT_SICUE', 'OUT_ERASMUS', 'OUT_MOVILIDAD_VIRTUAL_UNITA', 'OUT_MOVILIDAD_IBEROAMERICANA', 'OUT_NOA', 'OUT_OTROS', 'OUT_TOTAL', 'ALUMNOS_TIT_OUT'], 'integer'],
            [['P_TITULADOS_OUT'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ANO_ACADEMICO' => Yii::t('models', 'Ano  Academico'),
            'COD_CENTRO' => Yii::t('models', 'Cod  Centro'),
            'COD_ESTUDIO' => Yii::t('models', 'Cod  Estudio'),
            'IN_SICUE' => Yii::t('models', 'In  Sicue'),
            'IN_ERASMUS' => Yii::t('models', 'In  Erasmus'),
            'IN_MOVILIDAD_VIRTUAL_UNITA' => Yii::t('models', 'In  Movilidad  Virtual  Unita'),
            'IN_MOVILIDAD_RURAL_UNITA' => Yii::t('models', 'In  Movilidad  Rural  Unita'),
            'IN_MOVILIDAD_IBEROAMERICANA' => Yii::t('models', 'In  Movilidad  Iberoamericana'),
            'IN_NOA' => Yii::t('models', 'In  Noa'),
            'IN_OTROS' => Yii::t('models', 'In  Otros'),
            'IN_TOTAL' => Yii::t('models', 'In  Total'),
            'OUT_SICUE' => Yii::t('models', 'Out  Sicue'),
            'OUT_ERASMUS' => Yii::t('models', 'Out  Erasmus'),
            'OUT_MOVILIDAD_VIRTUAL_UNITA' => Yii::t('models', 'Out  Movilidad  Virtual  Unita'),
            'OUT_MOVILIDAD_IBEROAMERICANA' => Yii::t('models', 'Out  Movilidad  Iberoamericana'),
            'OUT_NOA' => Yii::t('models', 'Out  Noa'),
            'OUT_OTROS' => Yii::t('models', 'Out  Otros'),
            'OUT_TOTAL' => Yii::t('models', 'Out  Total'),
            'ALUMNOS_TIT_OUT' => Yii::t('models', 'Alumnos  Tit  Out'),
            'P_TITULADOS_OUT' => Yii::t('models', 'P  Titulados  Out'),
        ];
    }




}
