<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "notasPlan_lang".
 *
 * @property integer $id
 * @property integer $notasPlan_id
 * @property string $language
 * @property string $texto
 *
 * @property \app\models\NotasPlan $notasPlan
 * @property string $aliasModel
 */
abstract class NotasPlanLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'notasPlan_lang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['notasPlan_id'], 'required'],
            [['notasPlan_id'], 'integer'],
            [['texto'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['notasPlan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\NotasPlan::className(), 'targetAttribute' => ['notasPlan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'notasPlan_id' => Yii::t('models', 'Notas Plan ID'),
            'language' => Yii::t('models', 'Language'),
            'texto' => Yii::t('models', 'Texto'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNotasPlan()
    {
        return $this->hasOne(\app\models\NotasPlan::className(), ['id' => 'notasPlan_id']);
    }




}
