<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_nuevo_ingreso".
 *
 * @property integer $id
 * @property integer $ANO_ACADEMICO
 * @property integer $COD_ESTUDIO
 * @property integer $COD_CENTRO
 * @property integer $EP_PAU
 * @property integer $EP_COU
 * @property integer $EP_FP
 * @property integer $EP_TITULADO
 * @property integer $EP_MAY25
 * @property integer $EP_MAY40
 * @property integer $EP_MAY45
 * @property integer $EP_NO_CONSTA
 * @property integer $EP_EXTRANJERO
 * @property double $MED_PAU
 * @property double $MED_COU
 * @property integer $NUM_NUEVO_INGRESO_PRI
 * @property double $MED_FP
 * @property double $MED_TITULADO
 * @property double $MED_MAY25
 * @property double $MED_MAY40
 * @property double $MED_MAY45
 * @property double $NOTA_CORTE_1
 * @property double $NOTA_CORTE_2
 * @property integer $PLAZAS_OFERTADAS
 * @property integer $NUMERO_SOLICITUDES_1
 * @property integer $NUMERO_SOLICITUDES
 * @property integer $NUM_NUEVO_INGRESO
 * @property string $A_FECHA
 * @property integer $NUM_NI_COMUN_ARAGON
 * @property integer $NUM_NI_COMUN_NO_ARAGON
 * @property integer $NUM_NI_COMUN_NO_INFORMADO
 * @property integer $NUM_NI_PAIS_EEES
 * @property integer $NUM_NI_PAIS_NO_EEES
 * @property integer $NUM_NI_PAIS_NO_INFORMADO
 * @property integer $NUM_NI_SEXO_H
 * @property integer $NUM_NI_SEXO_M
 * @property integer $NUM_NI_SEXO_OTROS
 * @property integer $RE_18_24
 * @property integer $RE_25_29
 * @property integer $RE_30_34
 * @property integer $RE_MAS_35
 * @property string $aliasModel
 */
abstract class NuevoIngreso extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_nuevo_ingreso';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ANO_ACADEMICO', 'COD_ESTUDIO', 'COD_CENTRO', 'EP_PAU', 'EP_COU', 'EP_FP', 'EP_TITULADO', 'EP_MAY25', 'EP_MAY40', 'EP_MAY45', 'EP_NO_CONSTA', 'EP_EXTRANJERO', 'NUM_NUEVO_INGRESO_PRI', 'PLAZAS_OFERTADAS', 'NUMERO_SOLICITUDES_1', 'NUMERO_SOLICITUDES', 'NUM_NUEVO_INGRESO', 'NUM_NI_COMUN_ARAGON', 'NUM_NI_COMUN_NO_ARAGON', 'NUM_NI_COMUN_NO_INFORMADO', 'NUM_NI_PAIS_EEES', 'NUM_NI_PAIS_NO_EEES', 'NUM_NI_PAIS_NO_INFORMADO', 'NUM_NI_SEXO_H', 'NUM_NI_SEXO_M', 'NUM_NI_SEXO_OTROS', 'RE_18_24', 'RE_25_29', 'RE_30_34', 'RE_MAS_35'], 'integer'],
            [['MED_PAU', 'MED_COU', 'MED_FP', 'MED_TITULADO', 'MED_MAY25', 'MED_MAY40', 'MED_MAY45', 'NOTA_CORTE_1', 'NOTA_CORTE_2'], 'number'],
            [['A_FECHA'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ANO_ACADEMICO' => Yii::t('models', 'Ano  Academico'),
            'COD_ESTUDIO' => Yii::t('models', 'Cod  Estudio'),
            'COD_CENTRO' => Yii::t('models', 'Cod  Centro'),
            'EP_PAU' => Yii::t('models', 'Ep  Pau'),
            'EP_COU' => Yii::t('models', 'Ep  Cou'),
            'EP_FP' => Yii::t('models', 'Ep  Fp'),
            'EP_TITULADO' => Yii::t('models', 'Ep  Titulado'),
            'EP_MAY25' => Yii::t('models', 'Ep  May25'),
            'EP_MAY40' => Yii::t('models', 'Ep  May40'),
            'EP_MAY45' => Yii::t('models', 'Ep  May45'),
            'EP_NO_CONSTA' => Yii::t('models', 'Ep  No  Consta'),
            'EP_EXTRANJERO' => Yii::t('models', 'Ep  Extranjero'),
            'MED_PAU' => Yii::t('models', 'Med  Pau'),
            'MED_COU' => Yii::t('models', 'Med  Cou'),
            'NUM_NUEVO_INGRESO_PRI' => Yii::t('models', 'Num  Nuevo  Ingreso  Pri'),
            'MED_FP' => Yii::t('models', 'Med  Fp'),
            'MED_TITULADO' => Yii::t('models', 'Med  Titulado'),
            'MED_MAY25' => Yii::t('models', 'Med  May25'),
            'MED_MAY40' => Yii::t('models', 'Med  May40'),
            'MED_MAY45' => Yii::t('models', 'Med  May45'),
            'NOTA_CORTE_1' => Yii::t('models', 'Nota  Corte 1'),
            'NOTA_CORTE_2' => Yii::t('models', 'Nota  Corte 2'),
            'PLAZAS_OFERTADAS' => Yii::t('models', 'Plazas  Ofertadas'),
            'NUMERO_SOLICITUDES_1' => Yii::t('models', 'Numero  Solicitudes 1'),
            'NUMERO_SOLICITUDES' => Yii::t('models', 'Numero  Solicitudes'),
            'NUM_NUEVO_INGRESO' => Yii::t('models', 'Num  Nuevo  Ingreso'),
            'A_FECHA' => Yii::t('models', 'A  Fecha'),
            'NUM_NI_COMUN_ARAGON' => Yii::t('models', 'Num  Ni  Comun  Aragon'),
            'NUM_NI_COMUN_NO_ARAGON' => Yii::t('models', 'Num  Ni  Comun  No  Aragon'),
            'NUM_NI_COMUN_NO_INFORMADO' => Yii::t('models', 'Num  Ni  Comun  No  Informado'),
            'NUM_NI_PAIS_EEES' => Yii::t('models', 'Num  Ni  Pais  Eees'),
            'NUM_NI_PAIS_NO_EEES' => Yii::t('models', 'Num  Ni  Pais  No  Eees'),
            'NUM_NI_PAIS_NO_INFORMADO' => Yii::t('models', 'Num  Ni  Pais  No  Informado'),
            'NUM_NI_SEXO_H' => Yii::t('models', 'Num  Ni  Sexo  H'),
            'NUM_NI_SEXO_M' => Yii::t('models', 'Num  Ni  Sexo  M'),
            'NUM_NI_SEXO_OTROS' => Yii::t('models', 'Num  Ni  Sexo  Otros'),
            'RE_18_24' => Yii::t('models', 'Re 18 24'),
            'RE_25_29' => Yii::t('models', 'Re 25 29'),
            'RE_30_34' => Yii::t('models', 'Re 30 34'),
            'RE_MAS_35' => Yii::t('models', 'Re  Mas 35'),
        ];
    }




}
