<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "paim_opcion".
 *
 * @property string $id
 * @property integer $anyo
 * @property string $campo
 * @property string $tipo_estudio
 * @property string $valor
 *
 * @property \app\models\PlanRespuesta[] $planRespuestas
 * @property \app\models\PlanRespuesta[] $planRespuestas0
 * @property \app\models\PlanRespuesta[] $planRespuestas1
 * @property \app\models\PlanRespuesta[] $planRespuestas2
 * @property \app\models\PlanRespuesta[] $planRespuestas3
 * @property \app\models\PlanRespuesta[] $planRespuestas4
 * @property string $aliasModel
 */
abstract class PaimOpcion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'paim_opcion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['anyo', 'campo', 'tipo_estudio', 'valor'], 'required'],
            [['anyo'], 'integer'],
            [['campo', 'tipo_estudio'], 'string', 'max' => 31],
            [['valor'], 'string', 'max' => 127]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'anyo' => Yii::t('models', 'Anyo'),
            'campo' => Yii::t('models', 'Campo'),
            'tipo_estudio' => Yii::t('models', 'Tipo Estudio'),
            'valor' => Yii::t('models', 'Valor'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanRespuestas()
    {
        return $this->hasMany(\app\models\PlanRespuesta::className(), ['ambito_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanRespuestas0()
    {
        return $this->hasMany(\app\models\PlanRespuesta::className(), ['responsable_aprobacion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanRespuestas1()
    {
        return $this->hasMany(\app\models\PlanRespuesta::className(), ['plazo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanRespuestas2()
    {
        return $this->hasMany(\app\models\PlanRespuesta::className(), ['apartado_memoria_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanRespuestas3()
    {
        return $this->hasMany(\app\models\PlanRespuesta::className(), ['tipo_modificacion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanRespuestas4()
    {
        return $this->hasMany(\app\models\PlanRespuesta::className(), ['seguimiento_id' => 'id']);
    }




}
