<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_pas".
 *
 * @property integer $id
 * @property integer $ANO_ACADEMICO
 * @property string $ANIO_MES_STR
 * @property string $CENTRO
 * @property integer $COD_CENTRO
 * @property string $COD_CENTRO_RRHH
 * @property string $LOCALIDAD
 * @property string $ESPECIALIDAD
 * @property string $ID_ESPECIALIDAD_NK
 * @property string $TIPO_EMPLEADO
 * @property string $ID_TIPO_EMPLEADO_NK
 * @property integer $NUM_EMPLEADOS
 * @property string $aliasModel
 */
abstract class Pas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_pas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ANO_ACADEMICO', 'COD_CENTRO', 'NUM_EMPLEADOS'], 'integer'],
            [['ANIO_MES_STR', 'ID_ESPECIALIDAD_NK', 'ID_TIPO_EMPLEADO_NK'], 'string', 'max' => 7],
            [['CENTRO'], 'string', 'max' => 127],
            [['COD_CENTRO_RRHH'], 'string', 'max' => 4],
            [['LOCALIDAD'], 'string', 'max' => 50],
            [['ESPECIALIDAD', 'TIPO_EMPLEADO'], 'string', 'max' => 63]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ANO_ACADEMICO' => Yii::t('models', 'Ano  Academico'),
            'ANIO_MES_STR' => Yii::t('models', 'Anio  Mes  Str'),
            'CENTRO' => Yii::t('models', 'Centro'),
            'COD_CENTRO' => Yii::t('models', 'Cod  Centro'),
            'COD_CENTRO_RRHH' => Yii::t('models', 'Cod  Centro  Rrhh'),
            'LOCALIDAD' => Yii::t('models', 'Localidad'),
            'ESPECIALIDAD' => Yii::t('models', 'Especialidad'),
            'ID_ESPECIALIDAD_NK' => Yii::t('models', 'Id  Especialidad  Nk'),
            'TIPO_EMPLEADO' => Yii::t('models', 'Tipo  Empleado'),
            'ID_TIPO_EMPLEADO_NK' => Yii::t('models', 'Id  Tipo  Empleado  Nk'),
            'NUM_EMPLEADOS' => Yii::t('models', 'Num  Empleados'),
        ];
    }




}
