<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "plan_lang".
 *
 * @property integer $id
 * @property integer $plan_id
 * @property string $language
 * @property string $notas
 *
 * @property \app\models\Plan $plan
 * @property string $aliasModel
 */
abstract class PlanLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'plan_lang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['plan_id'], 'integer'],
            [['notas'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['plan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Plan::className(), 'targetAttribute' => ['plan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'plan_id' => Yii::t('models', 'Plan ID'),
            'language' => Yii::t('models', 'Language'),
            'notas' => Yii::t('models', 'Notas'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlan()
    {
        return $this->hasOne(\app\models\Plan::className(), ['id' => 'plan_id']);
    }




}
