<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use dosamigos\translateable\TranslateableBehavior;

/**
 * This is the base-model class for table "plan_pregunta".
 *
 * @property integer $id
 * @property integer $anyo
 * @property string $apartado
 * @property string $atributos
 * @property string $tipo
 * @property integer $oblig_def
 *
 * @property \app\models\PlanRespuesta[] $planRespuestas
 * @property string $aliasModel
 */
abstract class PlanPregunta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'plan_pregunta';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'translatable' => [
                'class' => TranslateableBehavior::className(),
                // in case you renamed your relation, you can setup its name
                // 'relation' => 'translations',
                'translationAttributes' => [
                    'titulo',
                    'explicacion'
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['anyo', 'oblig_def'], 'integer'],
            [['apartado', 'tipo'], 'string', 'max' => 15],
            [['atributos'], 'string', 'max' => 512]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'anyo' => Yii::t('models', 'Anyo'),
            'apartado' => Yii::t('models', 'Apartado'),
            'atributos' => Yii::t('models', 'Atributos'),
            'tipo' => Yii::t('models', 'Tipo'),
            'oblig_def' => Yii::t('models', 'Oblig Def'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'oblig_def' => Yii::t('models', 'Obligatorio en versión definitiva'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanRespuestas()
    {
        return $this->hasMany(\app\models\PlanRespuesta::className(), ['plan_pregunta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        return $this->hasMany(\app\models\PlanPreguntaLang::className(), ['plan_pregunta_id' => 'id']);
    }



}
