<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use dosamigos\translateable\TranslateableBehavior;

/**
 * This is the base-model class for table "plan".
 *
 * @property integer $id
 * @property integer $id_nk
 * @property integer $estudio_id
 * @property integer $centro_id
 * @property integer $creditos
 * @property integer $duracion
 * @property string $fecha_boe
 * @property string $normativa
 * @property string $nombre_coordinador
 * @property string $email_coordinador
 * @property integer $nip_coordinador
 * @property string $nombre_delegado
 * @property string $email_delegado
 * @property integer $activo
 * @property integer $en_extincion
 * @property integer $es_interuniversitario
 * @property integer $coordina_uz
 * @property integer $nuevo
 * @property string $url_horarios
 * @property string $url_web_plan
 * @property integer $compatible_men_esp
 * @property integer $anyo_academico
 * @property integer $estudio_id_nk
 *
 * @property \app\models\Centro $centro
 * @property \app\models\Estudio $estudio
 * @property string $aliasModel
 */
abstract class Plan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'plan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'translatable' => [
                'class' => TranslateableBehavior::className(),
                // in case you renamed your relation, you can setup its name
                // 'relation' => 'translations',
                'translationAttributes' => [
                    'notas'
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_nk'], 'required'],
            [['id_nk', 'estudio_id', 'centro_id', 'creditos', 'duracion', 'nip_coordinador', 'activo', 'en_extincion', 'es_interuniversitario', 'coordina_uz', 'nuevo', 'compatible_men_esp', 'anyo_academico', 'estudio_id_nk'], 'integer'],
            [['fecha_boe'], 'safe'],
            [['normativa'], 'string', 'max' => 25],
            [['nombre_coordinador', 'nombre_delegado'], 'string', 'max' => 127],
            [['email_coordinador', 'email_delegado'], 'string', 'max' => 254],
            [['url_horarios'], 'string', 'max' => 180],
            [['url_web_plan'], 'string', 'max' => 255],
            [['centro_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Centro::className(), 'targetAttribute' => ['centro_id' => 'id']],
            [['estudio_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Estudio::className(), 'targetAttribute' => ['estudio_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'id_nk' => Yii::t('models', 'Id Nk'),
            'estudio_id' => Yii::t('models', 'Estudio ID'),
            'centro_id' => Yii::t('models', 'Centro ID'),
            'creditos' => Yii::t('models', 'Creditos'),
            'duracion' => Yii::t('models', 'Duracion'),
            'fecha_boe' => Yii::t('models', 'Fecha Boe'),
            'normativa' => Yii::t('models', 'Normativa'),
            'nombre_coordinador' => Yii::t('models', 'Nombre Coordinador'),
            'email_coordinador' => Yii::t('models', 'Email Coordinador'),
            'nip_coordinador' => Yii::t('models', 'Nip Coordinador'),
            'nombre_delegado' => Yii::t('models', 'Nombre Delegado'),
            'email_delegado' => Yii::t('models', 'Email Delegado'),
            'activo' => Yii::t('models', 'Activo'),
            'en_extincion' => Yii::t('models', 'En Extincion'),
            'es_interuniversitario' => Yii::t('models', 'Es Interuniversitario'),
            'coordina_uz' => Yii::t('models', 'Coordina Uz'),
            'nuevo' => Yii::t('models', 'Nuevo'),
            'url_horarios' => Yii::t('models', 'Url Horarios'),
            'url_web_plan' => Yii::t('models', 'Url Web Plan'),
            'compatible_men_esp' => Yii::t('models', 'Compatible Men Esp'),
            'anyo_academico' => Yii::t('models', 'Anyo Academico'),
            'estudio_id_nk' => Yii::t('models', 'Estudio Id Nk'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCentro()
    {
        return $this->hasOne(\app\models\Centro::className(), ['id' => 'centro_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudio()
    {
        return $this->hasOne(\app\models\Estudio::className(), ['id' => 'estudio_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        return $this->hasMany(\app\models\PlanLang::className(), ['plan_id' => 'id']);
    }



}
