<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "plan_pregunta_lang".
 *
 * @property integer $id
 * @property integer $plan_pregunta_id
 * @property string $language
 * @property string $titulo
 * @property string $explicacion
 *
 * @property \app\models\PlanPregunta $planPregunta
 * @property string $aliasModel
 */
abstract class PlanPreguntaLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'plan_pregunta_lang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['plan_pregunta_id'], 'required'],
            [['plan_pregunta_id'], 'integer'],
            [['explicacion'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['titulo'], 'string', 'max' => 255],
            [['plan_pregunta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PlanPregunta::className(), 'targetAttribute' => ['plan_pregunta_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'plan_pregunta_id' => Yii::t('models', 'Plan Pregunta ID'),
            'language' => Yii::t('models', 'Language'),
            'titulo' => Yii::t('models', 'Titulo'),
            'explicacion' => Yii::t('models', 'Explicacion'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanPregunta()
    {
        return $this->hasOne(\app\models\PlanPregunta::className(), ['id' => 'plan_pregunta_id']);
    }




}
