<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "plan_respuesta_lang".
 *
 * @property integer $id
 * @property integer $plan_respuesta_id
 * @property string $language
 * @property string $apartado_memoria
 * @property string $titulo
 * @property string $descripcion_breve
 * @property string $descripcion_amplia
 * @property string $responsable_accion
 * @property string $inicio
 * @property string $final
 * @property string $responsable_competente
 * @property string $justificacion
 * @property string $nivel
 * @property string $fecha
 * @property string $problema
 * @property string $objetivo
 * @property string $acciones
 * @property string $plazo_implantacion
 * @property string $indicador
 * @property string $valores_a_alcanzar
 * @property string $valores_alcanzados
 * @property string $necesidad_detectada
 * @property string $observaciones
 * @property string $justificacion_breve
 *
 * @property \app\models\PlanRespuesta $planRespuesta
 * @property string $aliasModel
 */
abstract class PlanRespuestaLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'plan_respuesta_lang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['plan_respuesta_id'], 'required'],
            [['plan_respuesta_id'], 'integer'],
            [['descripcion_amplia', 'justificacion'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['apartado_memoria', 'titulo', 'responsable_accion', 'responsable_competente', 'valores_a_alcanzar', 'valores_alcanzados'], 'string', 'max' => 127],
            [['descripcion_breve', 'objetivo', 'observaciones', 'justificacion_breve'], 'string', 'max' => 350],
            [['inicio', 'final'], 'string', 'max' => 18],
            [['nivel'], 'string', 'max' => 2],
            [['fecha'], 'string', 'max' => 24],
            [['problema', 'acciones', 'plazo_implantacion', 'indicador', 'necesidad_detectada'], 'string', 'max' => 191],
            [['plan_respuesta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PlanRespuesta::className(), 'targetAttribute' => ['plan_respuesta_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'plan_respuesta_id' => Yii::t('models', 'Plan Respuesta ID'),
            'language' => Yii::t('models', 'Language'),
            'apartado_memoria' => Yii::t('models', 'Apartado Memoria'),
            'titulo' => Yii::t('models', 'Titulo'),
            'descripcion_breve' => Yii::t('models', 'Descripcion Breve'),
            'descripcion_amplia' => Yii::t('models', 'Descripcion Amplia'),
            'responsable_accion' => Yii::t('models', 'Responsable Accion'),
            'inicio' => Yii::t('models', 'Inicio'),
            'final' => Yii::t('models', 'Final'),
            'responsable_competente' => Yii::t('models', 'Responsable Competente'),
            'justificacion' => Yii::t('models', 'Justificacion'),
            'nivel' => Yii::t('models', 'Nivel'),
            'fecha' => Yii::t('models', 'Fecha'),
            'problema' => Yii::t('models', 'Problema'),
            'objetivo' => Yii::t('models', 'Objetivo'),
            'acciones' => Yii::t('models', 'Acciones'),
            'plazo_implantacion' => Yii::t('models', 'Plazo Implantacion'),
            'indicador' => Yii::t('models', 'Indicador'),
            'valores_a_alcanzar' => Yii::t('models', 'Valores A Alcanzar'),
            'valores_alcanzados' => Yii::t('models', 'Valores Alcanzados'),
            'necesidad_detectada' => Yii::t('models', 'Necesidad Detectada'),
            'observaciones' => Yii::t('models', 'Observaciones'),
            'justificacion_breve' => Yii::t('models', 'Justificacion Breve'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanRespuesta()
    {
        return $this->hasOne(\app\models\PlanRespuesta::className(), ['id' => 'plan_respuesta_id']);
    }




}
