<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "DATUZ_profesorado".
 *
 * @property integer $ano_academico
 * @property integer $cod_estudio
 * @property integer $cod_centro
 * @property string $categoria
 * @property integer $num_profesores
 * @property integer $num_permanentes
 * @property integer $num_en_primer_curso
 * @property integer $num_sexenios
 * @property integer $num_quinquenios
 * @property string $fecha_carga
 * @property double $porcentaje_profesor
 * @property double $horas_impartidas
 * @property double $porcentaje_horas
 * @property double $horas_personal_permanente
 * @property string $aliasModel
 */
abstract class Profesorado extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DATUZ_profesorado';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ano_academico', 'cod_estudio', 'cod_centro', 'num_profesores', 'num_permanentes', 'num_en_primer_curso', 'num_sexenios', 'num_quinquenios'], 'integer'],
            [['categoria'], 'string'],
            [['fecha_carga'], 'safe'],
            [['porcentaje_profesor', 'horas_impartidas', 'porcentaje_horas', 'horas_personal_permanente'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ano_academico' => Yii::t('models', 'Ano Academico'),
            'cod_estudio' => Yii::t('models', 'Cod Estudio'),
            'cod_centro' => Yii::t('models', 'Cod Centro'),
            'categoria' => Yii::t('models', 'Categoria'),
            'num_profesores' => Yii::t('models', 'Num Profesores'),
            'num_permanentes' => Yii::t('models', 'Num Permanentes'),
            'num_en_primer_curso' => Yii::t('models', 'Num En Primer Curso'),
            'num_sexenios' => Yii::t('models', 'Num Sexenios'),
            'num_quinquenios' => Yii::t('models', 'Num Quinquenios'),
            'fecha_carga' => Yii::t('models', 'Fecha Carga'),
            'porcentaje_profesor' => Yii::t('models', 'Porcentaje Profesor'),
            'horas_impartidas' => Yii::t('models', 'Horas Impartidas'),
            'porcentaje_horas' => Yii::t('models', 'Porcentaje Horas'),
            'horas_personal_permanente' => Yii::t('models', 'Horas Personal Permanente'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\ProfesoradoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\ProfesoradoQuery(get_called_class());
    }


}
