<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "rama_lang".
 *
 * @property integer $id
 * @property string $rama_id
 * @property string $language
 * @property string $nombre
 *
 * @property \app\models\Rama $rama
 * @property string $aliasModel
 */
abstract class RamaLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rama_lang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rama_id'], 'required'],
            [['rama_id'], 'string', 'max' => 1],
            [['language'], 'string', 'max' => 5],
            [['nombre'], 'string', 'max' => 255],
            [['rama_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Rama::className(), 'targetAttribute' => ['rama_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'rama_id' => Yii::t('models', 'Rama ID'),
            'language' => Yii::t('models', 'Language'),
            'nombre' => Yii::t('models', 'Nombre'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRama()
    {
        return $this->hasOne(\app\models\Rama::className(), ['id' => 'rama_id']);
    }




}
