<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "seccion".
 *
 * @property integer $id
 * @property integer $pagina
 * @property integer $orden
 * @property string $titulo
 * @property string $tipo
 *
 * @property \app\models\Informacion[] $informacions
 * @property string $aliasModel
 */
abstract class Seccion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'seccion';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id', 'pagina', 'orden'], 'integer'],
            [['titulo'], 'string', 'max' => 127],
            [['tipo'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'pagina' => Yii::t('models', 'Pagina'),
            'orden' => Yii::t('models', 'Orden'),
            'titulo' => Yii::t('models', 'Titulo'),
            'tipo' => Yii::t('models', 'Tipo'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInformacions()
    {
        return $this->hasMany(\app\models\Informacion::className(), ['seccion_id' => 'id']);
    }




}
