<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tipoEstudio_lang".
 *
 * @property integer $id
 * @property integer $tipoEstudio_id
 * @property string $language
 * @property string $nombre
 *
 * @property \app\models\TipoEstudio $tipoEstudio
 * @property string $aliasModel
 */
abstract class TipoEstudioLang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tipoEstudio_lang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tipoEstudio_id'], 'required'],
            [['tipoEstudio_id'], 'integer'],
            [['language'], 'string', 'max' => 5],
            [['nombre'], 'string', 'max' => 127],
            [['tipoEstudio_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoEstudio::className(), 'targetAttribute' => ['tipoEstudio_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'tipoEstudio_id' => Yii::t('models', 'Tipo Estudio ID'),
            'language' => Yii::t('models', 'Language'),
            'nombre' => Yii::t('models', 'Nombre'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoEstudio()
    {
        return $this->hasOne(\app\models\TipoEstudio::className(), ['id' => 'tipoEstudio_id']);
    }




}
