<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Aviso legal' => 'Legal warning',
    'Condiciones generales de uso' => 'General Use Conditions',
    'Política de privacidad' => 'Privacy Policy',
    'Servicio de Informática y Comunicaciones de la Universidad de Zaragoza' => 'ICT Service of the University of Zaragoza',
    'Universidad de Zaragoza' => 'University of Zaragoza',
    'Área de Aplicaciones. Servicio de Informática y Comunicaciones de la Universidad de Zaragoza.' => 'Area of applications. ICT Service of the University of Zaragoza',
    'Active' => '',
    'Ayuda' => '',
    'Año' => '',
    'Cerrar sesión' => '',
    'Contacte con nosotros si piensa que es un error del servidor. Gracias.' => '',
    'Editar' => '',
    'Gestión' => '',
    'Inactive' => '',
    'Informe de encuesta' => '',
    'Iniciar sesión' => '',
    'No tiene permisos para acceder a esta página. 😨' => '',
    'Off' => '',
    'On' => '',
    'Se produjo el error superior mientras el servidor web procesaba su petición.' => '',
    'You are not allowed to {0} record #{1}' => '',
];
