<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Centro' => 'Center',
    'Correo electrónico' => 'E-mail',
    'Cód. plan' => 'Plan code',
    'Estudio' => 'Degree',
    'Nombre y apellidos' => 'Full name',
    'Agentes' => '',
    'Are you sure to delete this item?' => '',
    'Cancel' => '',
    'Copy' => '',
    'Create' => '',
    'Cód. estudio' => '',
    'Delete' => '',
    'Edit' => '',
    'Fecha próxima renovación' => '',
    'First' => '',
    'Full list' => '',
    'Last' => '',
    'List All' => '',
    'New' => '',
    'Nuevo apartado' => '',
    'Nuevo delegado' => '',
    'Relations' => '',
    'Save' => '',
    'Select' => '',
    'URL de la acreditación institucional' => '',
    'URL de la web específica' => '',
    'URL del horario' => '',
    'View' => '',
];
