<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acceso, admisión y matrícula' => 'Entry Requirements and Enrolment',
    'Actividades formativas y movilidad' => 'Training Activities and Mobility',
    'Competencias' => 'Program Skills',
    'Equipos de investigación' => 'Research Teams',
    'Indicadores' => 'Stats',
    'Indicadores y resultados' => 'Statistics',
    'Informe de la Calidad de los Estudios de Doctorado y de sus diferentes Programas' => 'Quality Report of Doctoral Studies and its different Programs',
    'Líneas de investigación' => 'Research Lines',
    'Matrícula' => 'Enrolment',
    'Nuevo ingreso' => 'New Entry',
    'Perfil (CV) del PDI' => 'Researcher Resumé (CV)',
    'Profesorado. Líneas y equipos de investigación' => 'Teaching Staff, Lines and Research Teams',
    'Recursos y planificación' => 'Resources and Planning',
    'Resultados de la formación' => 'Scientific Results',
    'Satisfacción de los directores/tutores con el doctorado' => 'Directors and tutor satisfaction survey',
    'Satisfacción de los estudiantes con el doctorado' => 'Student satisfaction survey',
    'Supervisión y seguimiento' => 'Follow Up and Evaluation',
    'Todas' => 'All',
    ' Número total de los directores y directores de los estudiantes matriculados en el programa que tienen vinculación contractual con la Universidad de Zaragoza.' => '',
    'Anexo: Descripción de los indicadores' => '',
    'Coordinador (C), Comisión Académica (CA), Escuela de Doctorado (ED), Universidad de Zaragoza (UZ)' => '',
    'Encuestas a egresados doctorado 2016/2017. Resumen ejecutivo' => '',
    'Encuestas a egresados doctorado 2017/2018. Resumen ejecutivo' => '',
    'Indicador' => '',
    'Información gráfica del estudio' => '',
    'Informe de la Calidad de los Estudios de Doctorado y de sus diferentes Programas (ICED) del curso' => '',
    'Las definiciones detalladas de los indicadores están disponibles en un anexo al final del informe.' => '',
    'Número de aportaciones, por tesis, aceptadas el día de la defensa, incluyendo: artículos científicos en revistas indexadas, publicaciones (libros, capítulos de libros…) con sistema de revisión por pares y patentes.' => '',
    'Número de directores que han dirigido tesis defendidas en el programa de doctorado.' => '',
    'Número de estudiantes de nacionalidad extranjera matriculados en relación con el número total de estudiantes matriculados.' => '',
    'Número de estudiantes de nacionalidad extranjera matriculados en un programa de doctorado en relación con el número total de estudiantes matriculados en el programa de doctorado.' => '',
    'Número de estudiantes de nuevo ingreso que han formalizado su matrícula en un programa de doctorado a los que se les ha autorizado a desarrollar el trabajo de tesis a tiempo parcial en relación con el número de estudiantes de nuevo ingreso.' => '',
    'Número de estudiantes de nuevo ingreso que han requerido complementos formativos en relación con el número de estudiantes de nuevo ingreso en el programa de doctorado.' => '',
    'Número de estudiantes de nuevo ingreso que no proceden de estudios de acceso a doctorado de la misma universidad en relación con el número total de estudiantes de nuevo ingreso matriculados en el programa de doctorado.' => '',
    'Número de estudiantes de nuevo ingreso que no proceden de estudios de máster de la misma universidad en relación con el número total de estudiantes de nuevo ingreso matriculados en el programa de doctorado.' => '',
    'Número de estudiantes de nuevo ingreso.' => '',
    'Número de estudiantes de un programa de doctorado que, por primera vez, han formalizado la matrícula.' => '',
    'Número de estudiantes del programa de doctorado que han realizado estancias de investigación superiores a 3 meses en centros de investigación o en otras universidades en relación con el número total de estudiantes del programa de doctorado.' => '',
    'Número de estudiantes del programa de doctorado que han realizado, en el curso objeto del informe, estancias de investigación superiores a 3 meses en centros de investigación o en otras universidades en relación con el número total de estudiantes del programa de doctorado.' => '',
    'Número de estudiantes que durante un curso académico han defendido la tesis en régimen de cotutela en relación con el total de estudiantes que han defendido la tesis en ese mismo curso.' => '',
    'Número de estudiantes que durante un curso académico han defendido la tesis y han obtenido la calificación de cum laude en relación con el total de estudiantes que han defendido la tesis en ese mismo curso.' => '',
    'Número de estudiantes que durante un curso académico han defendido la tesis y que de acuerdo con los requisitos establecidos por la normativa han obtenido la mención de doctorado industrial de su título en relación con el total de estudiantes que han defendido la tesis en ese mismo curso.' => '',
    'Número de estudiantes que durante un curso académico han defendido la tesis y que de acuerdo con los requisitos establecidos por la normativa han obtenido la mención internacional de su título en relación con el total de estudiantes que han defendido la tesis en ese mismo curso.' => '',
    'Número de estudiantes que durante un curso académico han defendido la tesis y que de acuerdo con los requisitos establecidos por la normativa hanobtenido la mención de doctorado industrial de su título en relación conel total de estudiantes que han defendido la tesis en ese mismo curso.' => '',
    'Número de estudiantes que durante un curso académico ni han formalizado la matrícula en el programa de doctorado que cursaban ni han defendido la tesis en relación con el total de estudiantes que se podrían haber vuelto a matricular ese mismo curso.' => '',
    'Número de estudiantes que han formalizado su matrícula en un programa de doctorado a los que se les ha autorizado a desarrollar el trabajo de tesis a tiempo parcial en relación con el número total de estudiantes matriculados.' => '',
    'Número de estudiantes que han formalizado su matrícula en un programa de doctorado a los que se les ha autorizado a desarrollar el trabajo de tesis a tiempo parcial en relación con el número total de estudiantes.' => '',
    'Número de miembros internacionales en los tribunales de tesis defendidas en el curso objeto del estudio en relación con el número total de miembros de tribunales de tesis defendidas en el curso objeto del estudio.' => '',
    'Número de plazas que ofrece el programa de doctorado' => '',
    'Número de plazas que ofrece el programa de doctorado.' => '',
    'Número de proyectos de directores y tutores del programa vinculados contractualmente con la Universidad de Zaragoza financiados a cargo de programas u organismos internacionales que estén vigentes en el curso objeto del estudio.' => '',
    'Número de proyectos de directores y tutores del programa vinculados contractualmente con la Universidad de Zaragoza financiados a cargo de programas u organismos nacionales que estén vigentes en el curso objeto del estudio.' => '',
    'Número de publicaciones de directores y tutores del programa vinculados contractualmente con la Universidad de Zaragoza en revistas incluidas en catálogos que asignen índices de calidad relativos y que estén posicionadas en los cuartiles primero a cuarto de las revistas de su categoría.' => '',
    'Número de publicaciones de directores y tutores del programa vinculados contractualmente con la Universidad de Zaragoza en revistas no incluidas en catálogos qeu asignen índices de calidad relativos.' => '',
    'Número de sexenios de investigación obtenidos por los directores y tutores del programa de doctorado que tienen vinculación contractual con la Universidad de Zaragoza.' => '',
    'Número de solicitudes presentadas para acceder al programa de doctorado' => '',
    'Número de solicitudes presentadas para acceder al programa de doctorado.' => '',
    'Número de tesis defendidas por estudiantes del programa que no han requerido una primera prórroga de estudios en relación con el número total de tesis defendidas en el curso objeto de estudio.' => '',
    'Número de tesis defendidas por estudiantes del programa que no han requerido una segunda prórroga de estudios en relación con el número total de tesis defendidas en el curso objeto de estudio' => '',
    'Número de tesis defendidas por estudiantes del programa que no han requerido una segunda prórroga de estudios en relación con el número total de tesis defendidas en el curso objeto de estudio.' => '',
    'Número de tesis defendidas por los estudiantes del programa de doctorado a tiempo completo en el curso objeto del estudio.' => '',
    'Número de tesis defendidas por los estudiantes del programa de doctorado a tiempo parcial en el curso objeto del estudio.' => '',
    'Número medio de años empleados por los estudiantes a tiempo completo que han defendido la tesis en el programa desde que comenzaron sus estudios de doctorado en el programa.' => '',
    'Número medio de años empleados por los estudiantes a tiempo completo que han defendido la tesis en el programa desde que comenzaros sus estudios de doctorado en el programa.' => '',
    'Número medio de años empleados por los estudiantes a tiempo parcial que han defendido la tesis en el programa desde que comenzaros sus estudios de doctorado en el programa.' => '',
    'Número total de directores y tutores de los estudiantes matriculados en el programa.' => '',
    'Número total de estudiantes matriculados que en el curso de estudio están disfrutando de una beca o contrato predoctoral en relación con el número total de estudiantes matriculados.' => '',
    'Número total de estudiantes matriculados que en el curso de estudio estén disfrutando de una una beca o contrato predoctoral en relación con el número total de estudiantes matriculados.' => '',
    'Número total de estudiantes que en el curso de estudio hayan realizado actividades transversales en relación con el número total de estudiantes matriculados.' => '',
    'Número total de estudiantes que en el curso de estudio hayan realizado actividades transversales.' => '',
    'Número total de estudiantes que en un curso determinado han formalizado su matrícula en el programa de doctorado.' => '',
    'Número total de los directores y directores de los estudiantes matriculados en el programa que no tienen vinculación contractual con la Universidad de Zaragoza' => '',
    'Porcentaje de directores de tesis vinculados contractualmente con la Universidad de Zaragoza con sexenio vivo.' => '',
    'Porcentaje de directores y tutores del programa vinculados contractualmente con la Universidad de Zaragoza con dedicación a tiempo completo.' => '',
    'Porcentaje de directores y tutores del programa vinculados contractualmente con la Universidad de Zaragoza con sexenio vivo.' => '',
    'Satisfacción e inserción laboral de egresados de la Escuela de Doctorado' => '',
    'Web específica del programa' => '',
    'Expresar en forma de indicador para el seguimiento cuando sea posible.' => '',
];
