<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\PlanRespuestaLang $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="plan-respuesta-lang-form">

    <?php $form = ActiveForm::begin([
    'id' => 'PlanRespuestaLang',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute plan_respuesta_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'plan_respuesta_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PlanRespuesta::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['plan_respuesta_id'])),
    ]
); ?>

<!-- attribute descripcion_amplia -->
			<?= $form->field($model, 'descripcion_amplia')->textarea(['rows' => 6]) ?>

<!-- attribute justificacion -->
			<?= $form->field($model, 'justificacion')->textarea(['rows' => 6]) ?>

<!-- attribute language -->
			<?= $form->field($model, 'language')->textInput(['maxlength' => true]) ?>

<!-- attribute apartado_memoria -->
			<?= $form->field($model, 'apartado_memoria')->textInput(['maxlength' => true]) ?>

<!-- attribute titulo -->
			<?= $form->field($model, 'titulo')->textInput(['maxlength' => true]) ?>

<!-- attribute responsable_accion -->
			<?= $form->field($model, 'responsable_accion')->textInput(['maxlength' => true]) ?>

<!-- attribute responsable_competente -->
			<?= $form->field($model, 'responsable_competente')->textInput(['maxlength' => true]) ?>

<!-- attribute valores_a_alcanzar -->
			<?= $form->field($model, 'valores_a_alcanzar')->textInput(['maxlength' => true]) ?>

<!-- attribute valores_alcanzados -->
			<?= $form->field($model, 'valores_alcanzados')->textInput(['maxlength' => true]) ?>

<!-- attribute descripcion_breve -->
			<?= $form->field($model, 'descripcion_breve')->textInput(['maxlength' => true]) ?>

<!-- attribute objetivo -->
			<?= $form->field($model, 'objetivo')->textInput(['maxlength' => true]) ?>

<!-- attribute observaciones -->
			<?= $form->field($model, 'observaciones')->textInput(['maxlength' => true]) ?>

<!-- attribute justificacion_breve -->
			<?= $form->field($model, 'justificacion_breve')->textInput(['maxlength' => true]) ?>

<!-- attribute inicio -->
			<?= $form->field($model, 'inicio')->textInput(['maxlength' => true]) ?>

<!-- attribute final -->
			<?= $form->field($model, 'final')->textInput(['maxlength' => true]) ?>

<!-- attribute nivel -->
			<?= $form->field($model, 'nivel')->textInput(['maxlength' => true]) ?>

<!-- attribute fecha -->
			<?= $form->field($model, 'fecha')->textInput(['maxlength' => true]) ?>

<!-- attribute problema -->
			<?= $form->field($model, 'problema')->textInput(['maxlength' => true]) ?>

<!-- attribute acciones -->
			<?= $form->field($model, 'acciones')->textInput(['maxlength' => true]) ?>

<!-- attribute plazo_implantacion -->
			<?= $form->field($model, 'plazo_implantacion')->textInput(['maxlength' => true]) ?>

<!-- attribute indicador -->
			<?= $form->field($model, 'indicador')->textInput(['maxlength' => true]) ?>

<!-- attribute necesidad_detectada -->
			<?= $form->field($model, 'necesidad_detectada')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'PlanRespuestaLang'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

