<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\PlanRespuesta $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="plan-respuesta-form">

    <?php $form = ActiveForm::begin([
    'id' => 'PlanRespuesta',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute estudio_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'estudio_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Estudio::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['estudio_id'])),
    ]
); ?>

<!-- attribute plan_pregunta_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'plan_pregunta_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PlanPregunta::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['plan_pregunta_id'])),
    ]
); ?>

<!-- attribute anyo -->
			<?= $form->field($model, 'anyo')->textInput() ?>

<!-- attribute estudio_id_nk -->
			<?= $form->field($model, 'estudio_id_nk')->textInput() ?>

<!-- attribute cumplimiento -->
			<?= $form->field($model, 'cumplimiento')->textInput() ?>

<!-- attribute ambito_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'ambito_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PaimOpcion::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['ambito_id'])),
    ]
); ?>

<!-- attribute responsable_aprobacion_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'responsable_aprobacion_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PaimOpcion::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['responsable_aprobacion_id'])),
    ]
); ?>

<!-- attribute plazo_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'plazo_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PaimOpcion::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['plazo_id'])),
    ]
); ?>

<!-- attribute apartado_memoria_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'apartado_memoria_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PaimOpcion::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['apartado_memoria_id'])),
    ]
); ?>

<!-- attribute tipo_modificacion_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'tipo_modificacion_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PaimOpcion::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['tipo_modificacion_id'])),
    ]
); ?>

<!-- attribute seguimiento_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'seguimiento_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PaimOpcion::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['seguimiento_id'])),
    ]
); ?>

<!-- attribute estado_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'estado_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\PaimOpcion::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['estado_id'])),
    ]
); ?>

<!-- attribute apartado -->
			<?= $form->field($model, 'apartado')->textInput(['maxlength' => true]) ?>

<!-- attribute descripcion_amplia -->

<!-- attribute justificacion -->

<!-- attribute language -->

<!-- attribute apartado_memoria -->

<!-- attribute titulo -->

<!-- attribute responsable_accion -->

<!-- attribute responsable_competente -->

<!-- attribute valores_a_alcanzar -->

<!-- attribute valores_alcanzados -->

<!-- attribute inicio -->

<!-- attribute final -->

<!-- attribute nivel -->

<!-- attribute fecha -->

<!-- attribute problema -->

<!-- attribute acciones -->

<!-- attribute plazo_implantacion -->

<!-- attribute indicador -->

<!-- attribute necesidad_detectada -->

<!-- attribute descripcion_breve -->

<!-- attribute objetivo -->

<!-- attribute observaciones -->

<!-- attribute justificacion_breve -->
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'PlanRespuesta'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

