<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\PlanRespuesta $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('models', 'Plan Respuesta');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models', 'Plan Respuestas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="giiant-crud plan-respuesta-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('models', 'Plan Respuesta') ?>
        <small>
            <?= Html::encode($model->id) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('cruds', 'Edit'),
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('cruds', 'Copy'),
            ['create', 'id' => $model->id, 'PlanRespuesta'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New'),
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('cruds', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('app\models\PlanRespuesta'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'estudio_id',
    'value' => ($model->estudio ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['estudio/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->estudio->id, ['estudio/view', 'id' => $model->estudio->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['estudio_id' => $model->estudio_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'plan_pregunta_id',
    'value' => ($model->planPregunta ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['plan-pregunta/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->planPregunta->id, ['plan-pregunta/view', 'id' => $model->planPregunta->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['plan_pregunta_id' => $model->plan_pregunta_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'anyo',
        'estudio_id_nk',
        'cumplimiento',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'ambito_id',
    'value' => ($model->ambito ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['paim-opcion/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->ambito->id, ['paim-opcion/view', 'id' => $model->ambito->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['ambito_id' => $model->ambito_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'responsable_aprobacion_id',
    'value' => ($model->responsableAprobacion ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['paim-opcion/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->responsableAprobacion->id, ['paim-opcion/view', 'id' => $model->responsableAprobacion->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['responsable_aprobacion_id' => $model->responsable_aprobacion_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'plazo_id',
    'value' => ($model->plazo ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['paim-opcion/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->plazo->id, ['paim-opcion/view', 'id' => $model->plazo->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['plazo_id' => $model->plazo_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'apartado_memoria_id',
    'value' => ($model->apartadoMemoria ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['paim-opcion/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->apartadoMemoria->id, ['paim-opcion/view', 'id' => $model->apartadoMemoria->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['apartado_memoria_id' => $model->apartado_memoria_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'tipo_modificacion_id',
    'value' => ($model->tipoModificacion ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['paim-opcion/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->tipoModificacion->id, ['paim-opcion/view', 'id' => $model->tipoModificacion->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['tipo_modificacion_id' => $model->tipo_modificacion_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'seguimiento_id',
    'value' => ($model->seguimiento ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['paim-opcion/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->seguimiento->id, ['paim-opcion/view', 'id' => $model->seguimiento->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['seguimiento_id' => $model->seguimiento_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'estado_id',
    'value' => ($model->estado ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['paim-opcion/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->estado->id, ['paim-opcion/view', 'id' => $model->estado->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PlanRespuesta'=>['estado_id' => $model->estado_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'apartado',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('cruds', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('cruds', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('Translations'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('cruds', 'List All') . ' Translations',
            ['plan-respuesta-lang/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New') . ' Translation',
            ['plan-respuesta-lang/create', 'PlanRespuestaLang' => ['plan_respuesta_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-Translations', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Translations ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getTranslations(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-translations',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('cruds', 'First'),
        'lastPageLabel'  => Yii::t('cruds', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'plan-respuesta-lang' . '/' . $action;
        $params['PlanRespuestaLang'] = ['plan_respuesta_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'plan-respuesta-lang'
],
        'id',
        'language',
        'apartado_memoria',
        'titulo',
        'descripcion_breve',
        'descripcion_amplia:ntext',
        'responsable_accion',
        'inicio',
        'final',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.Html::encode($model->id).'</b>',
    'content' => $this->blocks['app\models\PlanRespuesta'],
    'active'  => true,
],
[
    'content' => $this->blocks['Translations'],
    'label'   => '<small>Translations <span class="badge badge-default">'. $model->getTranslations()->count() . '</span></small>',
    'active'  => false,
],
 ]
                 ]
    );
    ?>
</div>
